### ISSUE TITLE
Sterotype styling ignored in sub-diagrams

### ISSUE THREAD

**Issue by qslug** [plantuml/plantuml#1001]
This seems to have broken some time after 2022.1

The styles defined for stereotypes are no longer respected in sub-diagrams.

[Example](https://www.plantuml.com/plantuml/uml/TS_1oeCm30VmUvuYyBs6Y7nZXy5mCDnfx93PeCNQIfh2XlZkApleBkOKI7uX_oegYQRHGMyDOrGM3lgU620ErayaDA9mg-GxnqLnkJN7QrdY38XFQeTEGlBc45mG_6jw6zKnB3luLDVx-6oxNlzT-l8L8R-ctBDPzUym96LPdxe3ufnlvzfMgDL4RjE8om8FgDYRdFe3)

![image](https://user-images.githubusercontent.com/2030064/164216900-81fa4783-89b3-487a-bdbb-557ba1e9dd33.png)

**Comment by The-Lum** [comment]
Hello @qslug, and all,

In fact, it seems that the **sub-diagram** is independent of the host diagram, and have no link with the hosted (_root_) diagram.

---

See similar issue here:
- https://forum.plantuml.net/14963/sprite-in-subdiagram

Exception _(Except for some old `skinparam`)_:
- https://forum.plantuml.net/9043/skinparam-handwritten-inherited-within-embedded-diagram

---

Then, you must to repeat the `style` or `skinparam` directives on the begin of the **sub-diagram**, 
and adding `skinparam backgroundcolor transparent` _[due to isssue [QA-12821](https://forum.plantuml.net/12821)]_, as:
```puml
@startuml
hide stereotype

skinparam rectangle<<OUTER>> {
  backgroundColor #Thistle
}

skinparam rectangle<<INNER>> {
  backgroundColor #LightBlue
}

rectangle expected<<INNER>>

rectangle outer<<OUTER>>[
  {{
    hide stereotype
    skinparam rectangle<<INNER>> {
      backgroundColor #LightBlue
    }
    skinparam backgroundcolor transparent
    rectangle actual<<INNER>>
  }}
]
@enduml
```
>[![](https://www.plantuml.com/plantuml/svg/XOz1IiOm48NtSue1h_5JYk92a0fIL-9YJ8OsD4tAP09AoTrjksYbKDs5lFSDtwkJacWUFVJECYPbuQZV4mEamOM9X4OKDagXytoxlRorZwzLXJCWVf8PEeavs8Vee-1Tsxkadg5Sm4zDSmq_kwxNUvytV8UGlwRbpNQdVuSnAyikzGw8yteRyJnc_VjN2V5FhJKkfqj7tMnr5GffYJZerZnKoMWcVwn0B0K-eEPWy-X_0000)](https://www.plantuml.com/plantuml/uml/XOz1IiOm48NtSue1h_5JYk92a0fIL-9YJ8OsD4tAP09AoTrjksYbKDs5lFSDtwkJacWUFVJECYPbuQZV4mEamOM9X4OKDagXytoxlRorZwzLXJCWVf8PEeavs8Vee-1Tsxkadg5Sm4zDSmq_kwxNUvytV8UGlwRbpNQdVuSnAyikzGw8yteRyJnc_VjN2V5FhJKkfqj7tMnr5GffYJZerZnKoMWcVwn0B0K-eEPWy-X_0000)

Then here is a proposal without any **sub-diagram**:
```puml
@startuml
hide stereotype

skinparam rectangle<<OUTER>> {
  backgroundColor #Thistle
}

skinparam rectangle<<INNER>> {
  backgroundColor #LightBlue
}

rectangle expected<<INNER>>

rectangle "<U+200B>" <<OUTER>> {
    rectangle actual<<INNER>>
}
@enduml
```
>[![](https://www.plantuml.com/plantuml/svg/TSv12u9040NW-_wAmOvTfBE861s2C0Zz0PCxwEAuAxkpK8J_lUYWTV3suBqFNX44lSIHLMyqGH3ovEGvaL9XC7P2ZoDuQWLjnvHbrwO-tV8SNWhWZktGUHUjFZfs7dPrRu8mgNa3dwjg6rzCrql9ySiN1FIOFfdqed_B96lsXpGjymJ-hm6i8smb8gz-LWLP7KT-0m00)](https://www.plantuml.com/plantuml/uml/TSv12u9040NW-_wAmOvTfBE861s2C0Zz0PCxwEAuAxkpK8J_lUYWTV3suBqFNX44lSIHLMyqGH3ovEGvaL9XC7P2ZoDuQWLjnvHbrwO-tV8SNWhWZktGUHUjFZfs7dPrRu8mgNa3dwjg6rzCrql9ySiN1FIOFfdqed_B96lsXpGjymJ-hm6i8smb8gz-LWLP7KT-0m00)

Regards.
