### ISSUE TITLE
Allow colored sprites

### ISSUE THREAD

**Issue by Roemer** [plantuml/plantuml#119]
As the title says, it would be great to implement colored sprites instead of only grayscale sprites.

**Comment by arnaudroques** [comment]
Of course, that's something that we could implement.
However, we want to keep text-encoding sprites (because everything is text in PlantUML).
So we have to find a way to encode such colored sprites into texts, without having too large result.

For example, if we allow full 24 bit colors per pixel, this means that we would need 4 characters for a single pixel (using base64 chars), which would result in large result.

Following https://en.wikipedia.org/wiki/List_of_color_palettes we can try to *reduce* the number of colors.
If we limit the number of colors to [4096](https://en.wikipedia.org/wiki/List_of_monochrome_and_RGB_palettes#12-bit_RGB) , we could use only 2 characters per pixel.

Another solution would be to use indexed color ( https://en.wikipedia.org/wiki/Indexed_color ). We could then have 64 colors in the palette (using char A-Za-z0-9_-). However in that case we have to store the palette with the sprite, which takes also space.

Maybe you can post here some examples of sprites you'd like to use : this may help us to decide how to encode them.

Thanks!

**Comment by palashkulsh** [comment]
I mostly use sprites of frameworks/software logos to make diagrams more indulging. Like elasticsearch, consul. redis etc.

**Comment by hansmbakker** [comment]
I looks like there is assumed that sprites should be pixel-based and that that is the reason for not supporting better-looking images.

Would it not be possible to support SVGs in addition to text-defined sprites? Either inline svg or as a uri / filepath?

**Comment by evantill** [comment]
maybe something like a notation `:logo_github:` and a centralized repository (with a pragma to add a custom location if needed)

**Comment by arnaudroques** [comment]
Note that we do [now support SVG sprites](https://plantuml.com/en/sprite#5fa6c1055e0d0960).
We also [support Emoji](https://plantuml.com/en/creole#68305e25f5788db0).

I think we could close this issue.
Agree?

**Comment by palashkulsh** [comment]
Thanks @arnaudroques looks promising. Thanks for the great software : )
