### ISSUE TITLE
namespace are not inside each other 

### ISSUE THREAD

**Issue by T2brozz** [plantuml/plantuml#1233]
Hi guys,
so I created for a project a class diagram,  with multiple namespaces in eachother.
Now i want to extend a class from outside, and expected an arrow to from this class to the class in these namespaces, but for some reason plantuml is moving the inner namespace out.

![image](https://user-images.githubusercontent.com/42860763/209351853-afbe1f77-5597-44d2-938c-119d936d1868.png)

here is a small code to show my problem 
```plantuml
@startuml

namespace layer11{
    namespace layer12{
        namespace layer13{
            namespace layer14{
                class extern1 extends  layer21.layer22.layer23.layer24.d{
                }
            }
        }
    }
}
namespace layer21{
    namespace layer22{
        namespace layer23{
            namespace layer24{
                class d{
                }
            }
            class c{
                }
        }
        class b{
                }
    }
    class a{
                }
}

@enduml

```
has someone an idea why this is happening?

**Comment by The-Lum** [comment]
Hello @T2brozz, and all,

Yes...: In fact don't mix declaration and extension... But:

1. **First** define **`declaration`**.
2. **Then** define **`extension`**....

and observe a possible solution... as:

```puml
@startuml
namespace layer11{
    namespace layer12{
        namespace layer13{
            namespace layer14{
                class extern1 {
                }
            }
        }
    }
}
namespace layer21{
    namespace layer22{
        namespace layer23{
            namespace layer24{
                class d{
                }
            }
            class c{
            }
        }
        class b{
        }
    }
    class a{
    }
}

class layer11.layer12.layer13.layer14.extern1 extends  layer21.layer22.layer23.layer24.d
@enduml
```

>[![](https://www.planttext.com/api/plantuml/svg/ZL9H2iCW3FtFAJo1eFK0lKgc_baPwc13lFiiffMrjYm_pxoNm4lY71E6z5eSU5niVAAspE771Y4oi1f7MZPw94rT6idgLrv3EuoHsNUomGjsrWkCi_OgK8wkvTYrl7OjxrtBIzVcVxkzIUVRYNhX8v-6xIBcVNve39sCquq89qB5jnMlw4rasxOuhOUG6gJY1kPQMF_55m00)](https://www.planttext.com/?text=ZL9H2iCW3FtFAJo1eFK0lKgc_baPwc13lFiiffMrjYm_pxoNm4lY71E6z5eSU5niVAAspE771Y4oi1f7MZPw94rT6idgLrv3EuoHsNUomGjsrWkCi_OgK8wkvTYrl7OjxrtBIzVcVxkzIUVRYNhX8v-6xIBcVNve39sCquq89qB5jnMlw4rasxOuhOUG6gJY1kPQMF_55m00)

_Enjoy,_
Regards.

**Comment by T2brozz** [comment]
got it thanks

**Comment by BenceSzalai** [comment]
It is not only extensions. Any reference pointing to an element inside a nested namespace that comes before the declaration of those namespaces creates a "ghost" element. This is because PlantUML does not process fully qualified names for namespace separators. So any `extends` or just links pointing at `layer21.layer22.layer23.layer24.d` before the nested declaration will be understood as an element called `d` inside a namespace called `layer21.layer22.layer23.layer24`, instead of an element called `d` inside a namespace called `layer24` inside a namespace called `layer23` inside a namespace called `layer22` inside a namespace called `layer21`.

At least however when an element called `d` inside `layer24` inside `layer23`  inside `layer22`  inside `layer21` is already declared it will resolve the fully qualified name `layer21.layer22.layer23.layer24.d` to that element. So it really comes down to order:

Nested namespaces need to be declared before they are used.

See related issue here: https://github.com/plantuml/plantuml/issues/634
