### ISSUE TITLE
`@startregex` only shows last rule

### ISSUE THREAD

**Issue by albert-github** [plantuml/plantuml#1280]
In the question https://forum.plantuml.net/17357/documentation-of-hcl-and-regex some information was asked and given about the REGEX possibilities.
When trying a bit more complicated example (with PlantUML version 1.2023.1 (Sun Jan 29 13:58:56 CET 2023))  like:
```
@startregex
repetitionZeroOrMore a*
repetitionOneOrMore a+
@endregex
```
only the last rule is shown:

![bb](https://user-images.githubusercontent.com/5223533/215476216-9a721dde-30f5-471e-bcee-09bea2ecd629.png)

**Comment by arnaudroques** [comment]
Your issue is now part of the official [backlog](https://github.com/orgs/plantuml/projects/4). 
For technical reason, it has been put at `close` state but it's really still open for us.
You can by the way go on and put any comment in this issue.

The main reason why we put this issue in the backlog is that we try to group issues together so that we fix them together, as similar issues often impact the same code area.

Please be patient, but stay tuned! 🙂
