### ISSUE TITLE
Syntax error when including file with a mindmap

### ISSUE THREAD

**Issue by vladislavrv** [plantuml/plantuml#1289]
Here is the simple mindmap, and it works (let's call it `1.puml`):
```
@startmindmap

* 1
** 2
*** 3

@endmindmap
```
Here is actually the same mindmap, but enclosed into `startuml`/`enduml`. And it still works, 'cause why not?
```
@startuml
@startmindmap

* 1
** 2
*** 3

@endmindmap
@enduml
```
And here is conceptually the same diagram, but built by including first one into second one instead of copy-pasting it. And it does not work:
```
@startuml
!include 1.puml
@enduml
```
The error says
![3](https://user-images.githubusercontent.com/21141857/219398858-06b471da-a4e7-496a-98fd-6772a8f3403d.png)
so it looks like it swallowed `start/stopmindmap` tags and the diagram became invalid.

**Comment by The-Lum** [comment]
Hi @vladislavrv, and all,

It seems normal... _because_ `!include` seems to suppresses the `@start/@end` of the included files in order to include file diagram without breaking the hosted diagram.

_I.e.:_ each included file could be standalone or autonomous and the hosted diagram can host a lot of diagram with `!include`, while remaining only one big diagram (with only one `@start/@end`).... Otherwise it would break the `!include` functionality...

_If it is clear and If that can help,_
Regards.

**Comment by The-Lum** [comment]
Could you test with:

```puml
@startmindmap
!include 1.puml
@endmindmap
```

Regards.

**Comment by vladislavrv** [comment]
Well, sounds reasonable, and works for sure, thanks!
I was thinking about it for the usecase of including diagrams into `.md` file (e.g. gitlab integration) without actually knowing what type of diagram is inside. But... ye, looks like i have to know what's inside anyway.

**Comment by evantill** [comment]
Seems fixed. Can we close this issue ?
