### ISSUE TITLE
link between class and struct in different namespace

### ISSUE THREAD

**Issue by tianxingyang** [plantuml/plantuml#1293]
@startuml
namespace n_a {
class c_a
}
namespace n_b {
struct s_a
}
n_a.c_a ..> n_b.s_a
@enduml

**Comment by The-Lum** [comment]
Hi @tianxingyang, and all,

- What is your `plantuml` version?

Here is the expected result with last version (1.2023.2betaX):
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuSfBp4qjBaXCJbN8YqzKgEPApaaiBbP8Za_agaMHImBA5PSKbIQNA1H39ECJzO3A5FJqx43IUY3HjFpyajGYXR3KekBC_3mh1TKo24j3ayiXDIy5Q1y0)](https://www.planttext.com/?text=SoWkIImgAStDuSfBp4qjBaXCJbN8YqzKgEPApaaiBbP8Za_agaMHImBA5PSKbIQNA1H39ECJzO3A5FJqx43IUY3HjFpyajGYXR3KekBC_3mh1TKo24j3ayiXDIy5Q1y0)

See also:
>We have started a big refactoring concerning together/namespace/package. _(see https://plantuml.com/news)_
[link to: [#1282](https://github.com/plantuml/plantuml/issues/1282#issuecomment-1416392600)]

- Perhaps could you upgrade with the last version?

_If that can help,_
Regards.

**Comment by evantill** [comment]
@tianxingyang  is this fixed with the latest version ?

**Comment by tim-elmer** [comment]
While the original issue could be described better, I think I'm running into a similar problem. When attempting to create a link between a class and a struct defined in the default namespace, PlantUML gives the error message "ERROR / 259 / Cannot create <struct name> because it already exists".

```plantuml
@startuml
    namespace ns {
        class foo {
        }
        foo <-- .bar
    }

    struct bar {
    }
@enduml
```

This suggests to me that PlantUML is attempting to create a class based on its implied existence from the link (e.g. `class ns.foo <-- .bar` implies existence of `bar` in the default namespace), as it does not recognize that `bar` already exists as a struct in the default namespace.

Using `plantuml-1.2023.10`.

**Comment by arnaudroques** [comment]
This is because the implicit creation of bar in `ns.foo <-- .bar` create a class, not a struct.

A possible workaround is to define bar before:

```
@startuml
struct bar {
}

namespace ns {
        class foo {
        }
        foo <-- .bar
    }
@enduml
```

Is this an acceptable workaround for you?

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @tianxingyang, @tim-elmer for the report.
- Thanks @arnaudroques  for your answer.
- Thanks PlantUML team for your work.

Regards.
