### ISSUE TITLE
.repx file generation

### ISSUE THREAD

**Issue by tfc** [plantuml/plantuml#1296]
Hello,

I have seen those .repx files and did not find any documentation apart from the java source that extracts those for rendering.

How and when are these created? Are there any scripts?

I am interested in doing this myself.

**Comment by The-Lum** [comment]
Hello @tfc, and all,

Yes: there are no documentations about that, except the code and just some minor elements here:
- https://github.com/plantuml/plantuml/blob/master/stdlib/README.md

Then that transforms _(with Deflate/Brotli)_ this:
- https://github.com/plantuml/plantuml-stdlib

to this:
- https://github.com/plantuml/plantuml/tree/master/stdlib

```mermaid
flowchart LR

A[plantuml/plantuml-stdlib] -->|Brotli| B(plantuml/plantuml/tree/master/stdlib)

click A https://github.com/plantuml/plantuml-stdlib
click B https://github.com/plantuml/plantuml/tree/master/stdlib
```

See also _(mention of `.repx`)_ here: 
- https://github.com/plantuml/plantuml/issues/241#issuecomment-518035915

_If that can help,_
Regards.

**Comment by tfc** [comment]
So someone does this by hand? Is there a sequence of commands that are entered to perform an update or add a library to the .repx files?

**Comment by The-Lum** [comment]
Hi,
>So someone does this by hand?

Yes: The PlantUML team, @arnaudroques...

>Is there a sequence of commands that are entered to perform an update or add a library to the .repx files?

To add new library, you can propose PR on:
- https://github.com/plantuml/plantuml-stdlib

See also :
- https://github.com/plantuml/plantuml/issues/241#issuecomment-518035915

Regards.

**Comment by arnaudroques** [comment]
> > So someone does this by hand?
> 
> Yes: The PlantUML team, @arnaudroques...
> 

We do have indeed some scripts that generate those .repx files from https://github.com/plantuml/plantuml-stdlib

However, those scripts have not been published. There is no secret here, we just separate sprites and plain text in .puml files. We do some pre-treatement on sprites to improve compression and we finally use brotli.
The idea is to have the smallest files possible.

As I said, there is no secret here but the main reasons why this is not completely public:
1. This is a completely internal format which could be changed without any notification if we find a way to improve compression
2. We have a lot of other things to document before documenting this
3. There is no real reason for people to build .repx file since we are doing it for them

If you want to add new library, as @The-Lum said, you can propose PR on https://github.com/plantuml/plantuml-stdlib

Hope this helps!

**Comment by tfc** [comment]
If the person(s) who develop(s) the decompression algorithm, would commit the compression scripts together with the changed decompression code files, this would be extremely useful for users like me who would like to create their own pre-packaged plantuml versions from source (for example with company-internal libraries that are not for sharing because they contain proprietary symbols).

It would be completely forgivable, if this wasn't documented.

**Comment by arnaudroques** [comment]
> If the person(s) who develop(s) the decompression algorithm, would commit the compression scripts together with the changed decompression code files, this would be extremely useful for users like me who would like to create their own pre-packaged plantuml versions from source (for example with company-internal libraries that are not for sharing because they contain proprietary symbols).
> 
> It would be completely forgivable, if this wasn't documented.

Ok, in that case, we are going to provide the ability for users to add regular files in addition of those .repx files.
To clearly separate those non-standard files from the real standard library, the syntax will be slightly different:

`!include [foo/folder/file]`

This would look for the file `/stdlib/foo/folder/file.puml` from the .jar file

It's easy to implement on our side, I think it fulfills your need and the packaging will be really easy.

Any though?

**Comment by tfc** [comment]
Seems good to me.

Just out of curiosity, how much space does the repx thing save?

**Comment by arnaudroques** [comment]
> Just out of curiosity, how much space does the repx thing save?

About 30%? You can check-it by your self :-)

BTW, [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) now implements this `!include [foo/folder/file]` feature.

You just have to put some .puml file in /stdlib of the jar file.
Tell us if it's not working for you!

**Comment by snorrebrandstadmoen** [comment]
Hi @arnaudroques 

I've tried this approach (using several `plantuml` releases since February 2023), but always end up with a `cannot include foo/folder/file` rendering error (using the exact syntax `!include foo/folder/file`).

Do you have any more info on this feature? Or did it not make it to an actual release?
