### ISSUE TITLE
left footer is shifted to the right

### ISSUE THREAD

**Issue by user1095108** [plantuml/plantuml#1305]
If you write the following:
```
left footer
* one
* two
* three
endfooter
```
The footer will be shifted to the right, as if this was written:
```
left footer
* one
** two
*** three
endfooter
```

**Comment by The-Lum** [comment]
Hello @user1095108, and all,

_[The blue🔵 lines are only here for testing reasons]_

From your test:
```plantuml
title left footer
left footer
* one
* two
* three
----
* a b c
* a b
* a
endfooter
```
>[![](https://www.planttext.com/api/plantuml/svg/JOin2e1040FxVKLgGVo0sDZw2KyZ2iijd2iYujyzqS8KamIIUlL3sSXavamu1UYMoDRK4e9kb4lgwXlvuaee9yUxbtykO96Pljl3EP5IPkNI8s1u_Q4mZjz9RW00)](https://www.planttext.com/?text=JOin2e1040FxVKLgGVo0sDZw2KyZ2iijd2iYujyzqS8KamIIUlL3sSXavamu1UYMoDRK4e9kb4lgwXlvuaee9yUxbtykO96Pljl3EP5IPkNI8s1u_Q4mZjz9RW00)

We confirm that is the normal behaviour: because even if the legend is put to left, the text is always center aligned _(skin by default for footer on plantuml)_...

Then if you want :
- [x] `left footer`
- [x] and `left text alignment`

You can use style, as:
```plantuml
<style>
footer {
  HorizontalAlignment left
}
</style>
title left footer\nand left text align
left footer
* one
* two
* three
----
* a b c
* a b
* a
endfooter
```
>[![](https://www.planttext.com/api/plantuml/svg/JOoz2W9138JxF4LgGNo1Gn0R2n_1Pi-RquMOm3hY7xwxkzuLflZ293FJNVaqh6MC88g-HNKN9R_2cMnZ-UGNEDKmihxssR4DYwAztI0VwLPpdfc6dqsdgeCd7wO3yQ2crYL_1bbeE2fvZyPp0MHPfugalHwdtIZmOGx95m00)](https://www.planttext.com/?text=JOoz2W9138JxF4LgGNo1Gn0R2n_1Pi-RquMOm3hY7xwxkzuLflZ293FJNVaqh6MC88g-HNKN9R_2cMnZ-UGNEDKmihxssR4DYwAztI0VwLPpdfc6dqsdgeCd7wO3yQ2crYL_1bbeE2fvZyPp0MHPfugalHwdtIZmOGx95m00)

_Enjoy,_ 🎉 
Regards,
Th.
