### ISSUE TITLE
Non-Latin characters fail when used in "as" term

### ISSUE THREAD

**Issue by jeffkowalski** [plantuml/plantuml#1326]
The following script
```
@startuml
object "Kannada : bambu" as ಬಮ್ಬು
object bamboo
bamboo <-- ಬಮ್ಬು
@enduml
```
yields the following result
![image](https://user-images.githubusercontent.com/56880/225487634-b157a3be-bf8a-4528-88b5-c7a9f4c4455e.png)

**Comment by arnaudroques** [comment]
That's an interesting one!

First, non-latin character do work when used in "as" term. See [this](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuSfFoafDBb5GyaxCoqjCILImKaXAp4qgLL98B5PujgpfnR96g1AmU7u-5uHIiD7LXSaxfEQb08q20000) or [this](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuSfFoafDBb5GyaxCoqjCILImKaXAp4qgLL98B5Pui6dDWqthe4h0uldvN11AmKPN5oRla9gN0ZGA0000).

The issue comes from the fact that we are using the [unicode general category letter](https://en.wikipedia.org/wiki/Unicode_character_property#General_Category) to check if a character is a letter or not.

You example uses [Kannada script](https://en.wikipedia.org/wiki/Kannada_script) which is encoded in the [U+0C00 unicode block](https://en.wikipedia.org/wiki/Kannada_(Unicode_block)).

It contains the following characters:
ಮ U+0CAE
 U+0CCD
ಬ U+0CAC

The issue come from [U+0CCD](https://www.unicodepedia.com/unicode/kannada/ccd/kannada-sign-virama/) which is a modified letter and which is not considered as a *Letter* by Java Regex.
According to [this page](https://www.regular-expressions.info/unicode.html), the regex `\p{L}` should recognize U+0CCD.
Unfortunately, it is not.

**It's going to be hard to fix this one. Is this a big issue for you?**

Actually, you should talk to this in some Java forum. The following code shows clearly the behaviour:

```
public static void main(String[] args) {
	String cae = "\u0CAE";
	String ccd = "\u0CCD"; // https://www.unicodepedia.com/unicode/kannada/ccd/kannada-sign-virama/
	boolean isCaeLetter = cae.matches("^[\\p{L}]+$");
	boolean isCcdLetter = ccd.matches("^[\\p{L}]+$");
	System.err.println("isCaeLetter=" + isCaeLetter); // Print true, ok
	System.err.println("isCcdLetter=" + isCcdLetter); // Print false, not ok!
}
```

**Comment by arnaudroques** [comment]
Your issue is now part of the official [backlog](https://github.com/orgs/plantuml/projects/4). 
For technical reason, it has been put at `close` state but it's really still open for us.
You can by the way go on and put any comment in this issue.

The main reason why we put this issue in the backlog is that we try to group issues together so that we fix them together, as similar issues often impact the same code area.

Please be patient, but stay tuned! 🙂
