### ISSUE TITLE
Bug - Crowfoot notation on ERD rendering buggy

### ISSUE THREAD

**Issue by chatelao** [plantuml/plantuml#1353]
**Describe the bug**
Der crowfoot relation cardinality "||-o{" is rendered strange. More like "-o{||".

**To Reproduce**
1. Render this code:
```
entity DEPT {
**DEPTNO**: number(2), PK
}

entity EMP {
//DEPTNO//: number(2), FK
}

EMP::DEPTNO ||-o{ DEPT::DEPTNO
```

2. This is the result on https://www.planttext.com
![IyqhoIofL71n3GXHgERIqW8n_ForjAmKyafparABD8mqTHG2lBbgkRXI8KfTVGE0AlNr8IhrzL5Kke5L0fLOMK7a5MfgTFEhmUR3XBW0](https://user-images.githubusercontent.com/2461532/226986166-81b87513-5f29-4c13-9057-66117e39a635.png)

**Expected behavior**
Render the crowfoots as usual (i.e. described here):
https://plantuml.com/de/ie-diagram
![image](https://user-images.githubusercontent.com/2461532/226988760-63cd259e-ee2d-495f-ac81-68a0380b8117.png)
=> But exactly on the attribute "DEPTNO"

**Screenshots**
See above

**Desktop (please complete the following information):**
No idea, the error occurs in our Confluence (with plugin) as well as on "planttext.com".

**Comment by arnaudroques** [comment]
For the record, it's a bug on GraphViz: when minlen=0, for some reason, only one triangle is drawn.
Compare [minlen=1](https://www.plantuml.com/plantuml/uml/fPB1IiGm48RlVOeGhtKtTR5rrwQiqcWBWb8ZYek7gGqcaAObJN5LV7TRUX4FYZIGOVw1-MS-c6tdmBg-rbwbNYoq4lL6xT67rqb2I8XsdOHMq5Q3CaxidQ-X59h6CJyxls99p8lXfmXTv0yilSqV6SMyk6COtUSfpoWErmk2KSRoounJl0e7bSHBdewX-6zx42r2ibv5nnZTN1T3ePnZTlHZb-M4b3oTUXDzD9y-c4SV_4eFSyp-fj_0OJ9TmQRSLShIid7I1skRLmTAKr6txctIKa3rNNVgNT30hvNHmWp9SwCRI_416Ty97cTudzvMcAglzHS0) and [minlen=0](https://www.plantuml.com/plantuml/uml/fP9HIuH04CVV_HJBzcftQqVQNOvSeQKG5BPHTFGmvf8BwohhIbVHTq_n9Neeme4P-0_CV-O7i-qi6jlNoYdbYy6s8hsMU_BXT1LZp2Uxhi9MGAjGQYlsrbLO20LXoC_Ehv8evFcGCI4NsKCItsQF2L2UtoMKt6SnJu7wwmMZ94soovG3NVc3Yi8bZyUI_tVS2nO-Mw-2OqfkhlEXKSmnE_fnot92YfvEdOa-c4_lpQFtVgN7EMP_qs_mC9g-O5FiIccWQ6pbeZ7DgqMfGDIjVPjq9R3yhZlvBi1pQwcLqC3SvqOr1kW16-E4ZZkSJsShTDdNwWi0).

However, since it's really annoying, we are going to find a way to turn around this bug... stay tuned :-)
