### ISSUE TITLE
JSON Schema diagram

### ISSUE THREAD

**Issue by tomasbjerre** [plantuml/plantuml#1358]
**Describe the solution you'd like**
It currently has support for `JSON Data`. I think schema can be implemented by adjusting the existing code for JSON.

**Describe alternatives you've considered**
I've been googling how to visualize JSONSchema but cannot find any command line tool that can do that.

**Comment by arnaudroques** [comment]
Your issue is now part of the official [backlog](https://github.com/orgs/plantuml/projects/4). 
For technical reason, it has been put at `close` state but it's really still open for us.
You can by the way go on and put any comment in this issue.

The main reason why we put this issue in the backlog is that we try to group issues together so that we fix them together, as similar issues often impact the same code area.

Please be patient, but stay tuned! 🙂

**Comment by VladimirAlexiev** [comment]
@tomasbjerre What kind of diagram do you have in mind? Can you give some examples?

**Comment by tomasbjerre** [comment]
I found a json-diagram here:
https://improvingwetware.com/2021/01/24/plantuml-has-a-good-way-of-visualizing-json

# Nodes

Just like `address` is visualized as as separate node in that example, I want `$ref` visualized the same way.

Here is a `$ref`:
https://github.com/oasis-tcs/sarif-spec/blob/130e148d2eea6ec2b43c0e3deca1b5cfc9f9f4aa/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json#L27

It references:
https://github.com/oasis-tcs/sarif-spec/blob/130e148d2eea6ec2b43c0e3deca1b5cfc9f9f4aa/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json#L2326

# Content of nodes

Just like the `streetAddress` I want the properties the same way:
https://github.com/oasis-tcs/sarif-spec/blob/130e148d2eea6ec2b43c0e3deca1b5cfc9f9f4aa/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json#L2330

A table with 2 columns, name of property and the property type.

**Comment by evantill** [comment]
Some specification about [json references](http://jsonref.org/) (not sure if this is the official specification)
