### ISSUE TITLE
Add FTA "Fault Tree Analysis" diagram

### ISSUE THREAD

**Issue by SHU-red** [plantuml/plantuml#1364]
**Is your feature request related to a problem? Please describe.**
- I want to use plantuml for as many diagrams as possible
- Trying to create a FTA like [this](https://wcs.smartdraw.com/fault-tree/img/fault-tree-3.jpg?bn=1510011086) was not possible

**Describe the solution you'd like**
- new diagram-type for being able to create a FTA diagram

**Describe alternatives you've considered**
- Using Work Breakdown structure Diagram was not sufficient
- Other Programs/Tools are not feasible for me

**Comment by arnaudroques** [comment]
Your issue is now part of the official [backlog](https://github.com/orgs/plantuml/projects/4). 
For technical reason, it has been put at `close` state but it's really still open for us.
You can by the way go on and put any comment in this issue.

The main reason why we put this issue in the backlog is that we try to group issues together so that we fix them together, as similar issues often impact the same code area.

Please be patient, but stay tuned! 🙂

**Comment by SHU-red** [comment]
Thank you very much for taking this into the backlog
