### ISSUE TITLE
Hide/Show SubGraph

### ISSUE THREAD

**Issue by mohnishkodnani** [plantuml/plantuml#1366]
**Is your feature request related to a problem? Please describe.**
I have a very complex workflow that I describe programmatically in Java and then convert to SVG. I can group certain state in sub workflows, however, they still are seen making it really difficult to end users to understand the diagram. 
Currently using state diagram, open to using any other activity based diagram that can support workflows and show/hide feature. 
**Describe the solution you'd like**
I am looking for a way to hide/show this subworkflow only when clicked, so that the higher level diagram is as simple as possible. I am not even sure if this is possible, but wanted to check if anyone has an idea. 

**Describe alternatives you've considered**
Tried to research any other server side has this feature as well.But could not find one, I like the simplicity of plantuml so checking here for ideas.

**Additional context**

**Comment by swmatisa** [comment]
Hello,

For big diagram with substates, I create substates in different files and I
create links to substates:
@startuml
State S1 [[file:.\test1sub.svg]]
@enduml

**Comment by mohnishkodnani** [comment]
We do this programmatically and serve a rest endpoint. The workflow is
dynamic, so there are no files involved. We have graph that we convert to
plantuml and then convert to SVG.

**Comment by arnaudroques** [comment]
Your issue is now part of the official [backlog](https://github.com/orgs/plantuml/projects/4). 
For technical reason, it has been put at `close` state but it's really still open for us.
You can by the way go on and put any comment in this issue.

The main reason why we put this issue in the backlog is that we try to group issues together so that we fix them together, as similar issues often impact the same code area.

Please be patient, but stay tuned! 🙂
