### ISSUE TITLE
Sheet cache in CreoleParser is never cleaned

### ISSUE THREAD

**Issue by ggrossetie** [plantuml/plantuml#1368]
**Describe the bug**

We are using a cache to avoid creating a new sheet:
https://github.com/plantuml/plantuml/blob/32429afbb0c7c69ea772253a2851cd2871b5b99a/src/net/sourceforge/plantuml/klimt/creole/legacy/CreoleParser.java#L124-L133

The CreoleParser is also cached on `SkinParam`:

https://github.com/plantuml/plantuml/blob/32429afbb0c7c69ea772253a2851cd2871b5b99a/src/net/sourceforge/plantuml/skin/SkinParam.java#L1216-L1228

As a result, a long running process will eventually runs out of memory:

![image](https://user-images.githubusercontent.com/333276/228501305-b7a23b00-1814-4869-83f5-0fb203cade01.png)

**To Reproduce**

Run PlantUML long enough while sending diagrams which use Creole syntax.

**Expected behavior**

Cache should be clear when they are not used anymore (or should be configurable with a max size or a max element size). Guava Cache does a pretty good job: https://github.com/google/guava/wiki/CachesExplained

**Comment by arnaudroques** [comment]
Well, many thanks: you have definitively found something that is very dirty, you'll see :-)

However, both caches are **not** long term cache: they are local to object that are not long term object (they are not static).

So they should be removed by the GC once the diagram has been generated.

Now the reason why the first cache is [sometimes going big is clear](https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/klimt/creole/Display.java#L91).

**This code should never have been commented**: not sure why it get to the main branch.
So we will restore this `hashcode` so that the cache will actually work and do an official release in the incoming days.

Sorry about that!

**Comment by ggrossetie** [comment]
I wasn't sure why it was not GC, now I see 🙈
No worries, thanks for the quick fix!
