### ISSUE TITLE
Releases and automated builds

### ISSUE THREAD

**Issue by MOZGIII** [plantuml/plantuml#139]
Hey guys, I'd love to see this repo have built jars attached at github releases.

Best if everything's built automatically using CI.

Additionally, I'd love to see a docker image with a jar and all dependencies provided (for use with my Drone CI). But given the jar is provided through reliable and automated process and available for download via Github API, I can build my own docker image.

**Comment by anoff** [comment]
I am using [think/plantuml](https://github.com/lindt/docker_plantuml) to convert images without running a full server. It seems to be updated [regularly](https://hub.docker.com/r/think/plantuml/tags/)

Maybe you can use this in your CI jobs?

**Comment by karfau** [comment]
The regular updates of think/plantuml are a strange thing, since the latest version is still 1.2020.5.
I looked at several alternatives and also at [a suggestion from the "Forum"](https://forum.plantuml.net/11186/please-publish-official-docker-supports-headless-operation?show=11186#q11186) to pick the best things from all of them.

Since from the side of plantuml nothing happened for years regarding this issue, I created an alternative: [karfau/plantuml](https://hub.docker.com/r/karfau/plantuml) / https://github.com/karfau/plantuml-docker that will be updated whenever a new version of plantuml is out (thx to renovatebot for supporting java and so many options). 
To prove that I started of with version 1.2020.0 and the latest version should be out there soon.

There is still some documentation missing but it will follow and PRs are welcome.

**Comment by MOZGIII** [comment]
I forgot about this issue! Since I created it, I made my own automation for publishing plantuml docker images: https://github.com/MOZGIII/plantuml-docker

**Comment by karfau** [comment]
Cool, so this one just fetches the latest jar from stackoverflow and triggers a build every day on docker hub. Nice simple solution.

**Comment by MOZGIII** [comment]
Yep. I've got a message from Github that they're pausing nightly builds on that repo recently though - so the process might've stalled.
So, it still would be better to build off of the upstream.

It's 2020, two years since I created the original issue. I would hope it's now clear that the demand is there, and the implementation is super trivial.

**Comment by karfau** [comment]
Yes, there are quite some outdated docker images out there, an official one would make sure it's up to date...

**Comment by gliptak** [comment]
https://github.com/plantuml/plantuml/pkgs/container/plantuml is available

consider closing

**Comment by karfau** [comment]
@gliptak is there any documentation on how to use it?
From building my own docker image for it, the usage is often not obvious, compared to the cli.

The link you provided just shows the normal readme.

**Comment by gliptak** [comment]
@karfau I do see your usage documentation at https://github.com/karfau/plantuml-docker maybe you are to submit a documentation PR

**Comment by karfau** [comment]
@gliptak is there any documentation on how to use it?
From building my own docker image for it, the usage is often not obvious, compared to the cli.

The link you provided just shows the normal readme.

(The version in the image is not pointing to the latest by the way.)

**Comment by MOZGIII** [comment]
Yep, finally, we have https://github.com/plantuml/plantuml/pkgs/container/plantuml
