### ISSUE TITLE
License headers not being added by preprocessor

### ISSUE THREAD

**Issue by alfonsodelavega** [plantuml/plantuml#1505]
**Describe the bug**
In each licensed release of PlantUML, Java sources do not include the license header, but instead they contain the generic message `// THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.`

Only the GPL-licensed sources have the header, which I believe is the one from the original sources so the preprocesor might not intervene for those.

Strangely, the `1.2023.7` version that can be found in the website has the proper license headers for e.g. EPL.

**To Reproduce**

Open any Java file in a release from `1.2023.10` to `1.2023.7` (including the current snapshot). I checked the EPL and MIT-licensed ones.

**Expected behavior**

I believe the expected preprocessor behavior was to place the corresponding header for each license. I am willing to help fix the preprocessor if needed.

**Context**

Somewhat related to #1396.

**Comment by arnaudroques** [comment]
> I've taken a look and seen that `sjpp` directives are used to manage how sources of each version are automatically generated (via an ant task in each gradle build).
> 

Yes. So somehow this issue is related to [sjpp](https://github.com/plantuml/sjpp).

> No directives are present at the start of each file to `::comment` / `:uncomment` license headers, as I assume this is avoided in favour of simplicity. 

Yes, and we have been lazy here: by default, [sjpp](https://github.com/plantuml/sjpp) systematically remove the header of all Java files.

We should probably change this behavior. Optionally, we could provide an option to the ANT task with some file that would contain the header to be inserted on all generated Java files;

```
<target name="dist">
	<sjpp src="src-folder" dest="src-generated" define="__MIT__"  header="mit_header_content.txt" />
</target>
```

Where `mit_header_content.txt` would be a text file containing the MIT license.


> I see that a `License.java` file with the proper license header is created for each `build` folder, but I was not able to follow where this file is used. Is the plan using it to prepend the license header to each file?
> 
Well no. This is really legacy code (this was used before sjpp). We should clean stuff there.

> Am I in the right track? As I said, I'm happy to help with this issue.

So yes, you are in the right track.
If you still want to help, here is what you can do:
1. Create an issue/discussion on [sjpp](https://github.com/plantuml/sjpp) so that we can clearly specify the new `header="somefile.txt"` 
2. Code yourself a PR to [sjpp](https://github.com/plantuml/sjpp) with this new feature
3. Using the new sjpp for PlantUML generation would then be peace of cake :-)

Does it sound good?

**Comment by alfonsodelavega** [comment]
> Does it sound good?

Sounds great! I'll give it a go. Thanks for the explanations!

I'll create the issue at sjpp and link it here to trace the conversations around this.
