### ISSUE TITLE
Error when drawing arrow linestyle with specific measures in gantt diagrams

### ISSUE THREAD

**Issue by kkrafft1999** [plantuml/plantuml#1595]
**Describe the bug**
When I put an arrow styling within the gannt diagram style:
```puml
@startgantt
<style>
ganttDiagram {
	arrow {
        LineStyle 8.0;13.0
	}
}
</style>
...
@endgantt
```

This result in a pasrsing error.

**To Reproduce**

Just put the styling above in your pgantt diagram

**Expected behavior**
Arrows should be drawn with the specific styling linestyle parameters

**Screenshots**
<img width="185" alt="image" src="https://github.com/plantuml/plantuml/assets/16942747/ad92699f-bf0a-4e42-b84a-68038bb0f5a7">

**Desktop (please complete the following information):**

- Windows 10

**Comment by laurateixeir** [comment]
After reviewing the guide and the documentation for the gantt diagramm and checking the code i found out that it is possible to apply the linestyle. Instead of a semicolon it is possible to just use a dash. When using the dash the Linestyle 8.0-13.0 is slightly different from using 8.0;13.0. 

This is because the LineStyle only can be set like that when **LineThickness** is set also. Somehow the LineStyle relies on the LineThickness. I am still trying to figure out where in the code this is set. 

### With dash:
`@startgantt

<style>
timeline {
    BackGroundColor Grey
    FontName Helvetica
    FontSize 20
    FontColor Blue
}
arrow {

    LineStyle 8.0-13.0

}

</style>

[Task1] lasts 20 days
note bottom
 memo1 ...
 memo2 ...
 explanations1 ...
 explanations2 ...
end note

[Task2] lasts 4 days
[Task2] starts 3 days after [Task1]'s end
[Task1] -> [Task2]
-- Seperator Title --

[M1] happens on 5 days after [Task1]'s end

-- end --

@endgantt`

**Output:**

![grafik](https://github.com/plantuml/plantuml/assets/115394190/a3b6ab93-08f8-4df1-abe3-09ca47c41afd)


### With LineThickness:

`@startgantt

<style>
timeline {
    BackGroundColor Grey
    FontName Helvetica
    FontSize 20
    FontColor Blue
}
arrow {
    LineStyle 8.0;13.0
    LineThickness 1.0
}

</style>

[Task1] lasts 20 days
note bottom
 memo1 ...
 memo2 ...
 explanations1 ...
 explanations2 ...
end note

[Task2] lasts 4 days
[Task2] starts 3 days after [Task1]'s end
[Task1] -> [Task2]
-- Seperator Title --

[M1] happens on 5 days after [Task1]'s end

-- end --

@endgantt`



**Output:**

![grafik](https://github.com/plantuml/plantuml/assets/115394190/ae68b561-4541-4b24-81bd-8f01b7f67eb5)

**Comment by laurateixeir** [comment]
In the class UStroke (package net.sourceforge.plantuml.klimt;) i found the dependency for the Linethickness.

```
	public UStroke(double dashVisible, double dashSpace, double thickness) {
		this.dashVisible = dashVisible;
		this.dashSpace = dashSpace;
		this.thickness = thickness;
	}
```


also you can see here in the class GantArrow (package net.sourceforge.plantuml.project;) in the method **drawU** that the Thickness is given here so this could be the reason why it is not possible to set the measure without it.

```
		ug = ug.apply(UStroke.withThickness(1.5)).apply(style.value(PName.LineColor).asColor(colorSet).bg());

```

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @kkrafft1999 for the report.
- Thanks @laurateixeir for your answer.

And FYI: the `LineThickness` parameter on style definition is well taken into account, as:
```puml
@startgantt
<style>
arrow {
  LineThickness 5
  LineStyle 8.0-13.0
  Linecolor green
}
</style>
[Task1] requires 2 days
then [Task2] requires 4 days
-- Phase Two --
then [Task3] requires 5 days
then [Task4] requires 6 days
@endgantt
```
>[![](https://www.planttext.com/api/plantuml/svg/NOzD2i8m44RtSugvG6f_nKMH7i25O7VY8hH3KreId8cK8jvTRBC8Rh_tUF0ruZNxGLlleHQ_pdG6pUmMV0FYPRJKch6RB8bW5PRRJyDJaggiID8mTcvsZ0CJMVX0VGWjkBTQfko1JC_No2IOOwzN0M_8uWRp29OxL0glHWjXkpXKAfABIAx-IsK4Zpk4Xco_tVi2)](https://www.planttext.com/?text=NOzD2i8m44RtSugvG6f_nKMH7i25O7VY8hH3KreId8cK8jvTRBC8Rh_tUF0ruZNxGLlleHQ_pdG6pUmMV0FYPRJKch6RB8bW5PRRJyDJaggiID8mTcvsZ0CJMVX0VGWjkBTQfko1JC_No2IOOwzN0M_8uWRp29OxL0glHWjXkpXKAfABIAx-IsK4Zpk4Xco_tVi2) 

_Enjoy,_
Regards,
Th.
