### ISSUE TITLE
[Preproc] Side effect of variable management when using `%json_add`

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1783]
Hello PlantUML team, and @arnaudroques,

During more testing on `%json_add`:
- #1742
- #1757

It seems there are some side effects... about variable management...

Here is a minimal _(not working)_ example:
```puml
@startuml
title Why $a and $b are modified?

!$a = [0,1]
!$b = %json_add($a, 5)
!$c = %json_add($a, 6)

json a {
"value":$a
}
json b {
"value":$b
}
json c {
"value":$c
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/PSv12i8m48NX_PnYB2aqq8KkT268lOKB4PaaKuoq2IHfGSIxEo92mTtFzpQlouLIcSO1YYy3u-dsG4L8mQ4oI8bnZCxtdjqHO2NB0S_hTdEHDjBrFSTm9USQHIrkjR3zuvq6-00IFg6QQPYusYk2rrVDKirFxLAjAFGn5avOpvooZw7Hq75mSlqD)](https://www.planttext.com/?text=PSv12i8m48NX_PnYB2aqq8KkT268lOKB4PaaKuoq2IHfGSIxEo92mTtFzpQlouLIcSO1YYy3u-dsG4L8mQ4oI8bnZCxtdjqHO2NB0S_hTdEHDjBrFSTm9USQHIrkjR3zuvq6-00IFg6QQPYusYk2rrVDKirFxLAjAFGn5avOpvooZw7Hq75mSlqD) 

It seems that the variables are modified in place...

Perhaps I missed something...
- How are managed variable on the preprocessor?
- and variable affectation and value modification...

@arnaudroques: Thanks to have a look... 👀 😃 

Regards,
Th.

**Comment by The-Lum** [comment]
_Maybe I place the preprocessor not far and beyond its limits..._

**Comment by arnaudroques** [comment]
> _Maybe I place the preprocessor not far and beyond its limits..._

No, don't worry: I think it's just an issue of cloning objects and sharing references.
I'll have a look at it :-)

**Comment by The-Lum** [comment]
> No, don't worry: I think it's just an issue of cloning objects and sharing references.
I'll have a look at it :-)

Yes, maybe I should make copies of the argument values before working on them...

**Comment by arnaudroques** [comment]
So I have added a `cloneMe()` method on `JsonValue` class. (see https://github.com/plantuml/plantuml/commit/d8f194d2d256743583cfc737a1198c987e99a27d).

However, it is possible (likely?) that this `cloneMe()` method should be used in other stdlib functions implementation.

@The-Lum I let you check! :-)

**Comment by The-Lum** [comment]
Hello @arnaudroques,

Thank you very much, I wouldn't have done it alone.
I'm not as agile with _clone_ or _deep copy_...

---

Here are some remarks or questions:

I might also have been able to make copies, as:
https://github.com/ralfstx/minimal-json/blob/c091e6985620da04d5abcd902aafb6c9583c48ea/com.eclipsesource.json/src/test/java/com/eclipsesource/json/JsonArray_Test.java#L59-L73

but your solution may be perhaps better, more global and consistent with the other cases in plantuml...
- https://github.com/search?q=repo%3Aplantuml%2Fplantuml%20cloneMe&type=code

But just a _[newbie]_ question:
- Why your `cloneMe` method _(on `JsonArray.java`)_ is not just:

```java
public JsonValue cloneMe() {
	return new JsonArray(this);
}
```

instead of:
https://github.com/plantuml/plantuml/blob/d8f194d2d256743583cfc737a1198c987e99a27d/src/net/sourceforge/plantuml/json/JsonArray.java#L73-L78

---

>However, it is possible (likely?) that this `cloneMe()` method should be used in other stdlib functions implementation.

Also yes: it will be necessary to add it where all the modifications is done on themselves or in place... (where you don't use new constructor!)... _[I can take the action...]_


_Thanks for your work and your answer..._ 🙏 
Regards,
Th.

**Comment by arnaudroques** [comment]
> * Why your `cloneMe` method _(on `JsonArray.java`)_ is not just:


That is the difference between deep copy (the code I've commited) and shallow copy (your example):

### Shallow Copy

A shallow copy creates a new object, but does not create copies of objects that are referenced within the original object. Instead, it copies the references to those objects. This means that the new object will share the same references to the nested objects as the original. If any of the nested objects are modified, the changes will be reflected in both the original and the copied object because they are pointing to the same nested objects.

#### Key Points:
- **New object is created**: Yes
- **Nested objects are copied**: No, only references to them are copied
- **Independence of objects**: Only the top-level object is independent; nested objects are shared
- **Impact of changes**: Changes to nested objects affect both the original and the shallow copy

### Deep Copy

A deep copy creates a new object and also recursively creates copies of all objects that are referenced by the original object. This means that the new object and all objects within it are entirely independent of the original object. Any changes made to the nested objects of the deep copy will not affect the nested objects of the original object, and vice versa.

#### Key Points:
- **New object is created**: Yes
- **Nested objects are copied**: Yes, all nested objects are recursively copied
- **Independence of objects**: Both the top-level object and all nested objects are independent
- **Impact of changes**: Changes to any part of the deep copy do not affect the original object

### Summary of Differences

- **Structure**: A shallow copy replicates the top-level structure but shares the nested objects, whereas a deep copy replicates the entire structure, including all nested objects.
- **Memory**: Shallow copy is faster and uses less memory because it does not create copies of nested objects. Deep copy is slower and uses more memory as it duplicates everything.
- **Use Cases**: Shallow copy is useful when you need a copy of the top-level object but are okay with sharing nested objects. Deep copy is essential when you need a completely independent copy of the original object, including all nested elements.

For further reading and more detailed explanations, you can visit the following resource [Baeldung: Shallow Copy and Deep Copy in Java](https://www.baeldung.com/java-deep-copy).

Tell me if you need some more information, there are no silly questions :-)

> Also yes: it will be necessary to add it where all the modifications is done on themselves or in place... (where you don't use new constructor!)... _[I can take the action...]_

Yes, please take the action if possible :-)

**Comment by The-Lum** [comment]
Thank you so much. 
_[I learn more every day...]_

Now: I can go to the code and to the documentation...

Regards,
Th.
