### ISSUE TITLE
[Seq] Allow `>>` and `>` on the same arrow

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1804]
## Context
To follow:
- #1678
- [QA-18958 - [Seq] Cannot have two end of Arrow having different style](https://forum.plantuml.net/18958/sequence-diagram-cannot-have-arrow-having-different-style)

## Wanted feature
- Could you allow `>>` and `>` on the same arrow, on seq. diag.?

## Example (on V1.2025.5)

```puml
@startuml
Test -->> Test: OK
Test <<-- Test: OK
Test <<-->> Test: the arrow is KO
Test <<->> Test: the arrow is KO
Test <<--> Test: the arrow is KO
Test <->> Test: the arrow is KO
Test <<-> a: the arrow is KO
Test <->> a: the arrow is KO
Test <<--> a: the arrow is KO
Test <-->> a: the arrow is KO
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuGf9BIvHqDMrirC0iQmK_BqXGZOskhfOXE3gIZ9I5HABYlBB5JAB5RpzuIe8Aj35hu086nGIyMd6AGcs6hTM77eTKlDIWE440000)](https://www.planttext.com/?text=SoWkIImgAStDuGf9BIvHqDMrirC0iQmK_BqXGZOskhfOXE3gIZ9I5HABYlBB5JAB5RpzuIe8Aj35hu086nGIyMd6AGcs6hTM77eTKlDIWE440000) 

_[FYI @jimnelson372]_
Regards,
Th.

**Comment by jimnelson372** [comment]
Hi @The-Lum,

Yes, I see in the code that when the message instruction for two ended arrows is being processed, it is currently assuming that if either arrow is async, then both are async.   I believe that can be fixed without too much difficulty, other than verifying that nothing else depends on this.   Right now, I'm unclear about the semantics of a double arrow on a sequence diagram, but if users find it to be meaningful and useful, then it should support the variety of arrows.

However, I'm not understanding what would be expected on the self-messages, since they should probably not even allow double ended arrows.   Self messages only go one way in the timeline.   From your example, it does look like PlantUML currently defaults to the right side self message arrow if given a double sided arrow, though I think only the <<--> self message is confusing in that though the right side arrow is not async, the left side arrow, which is ignored for drawing, is still causing the result to be an async arrow.   That would be fixed if the instruction evaluates whether each side is async separately, but I believe it should still ignore the left side arrow in these cases.   Please explain if I'm wrong about this.

Regards,

Jim N.
@jimnelson372

**Comment by The-Lum** [comment]
Hi @jimnelson372,

Thanks for your explanation;
I had just reported the problem of:
- [QA-18958 - [Seq] Cannot have two end of Arrow having different style](https://forum.plantuml.net/18958/sequence-diagram-cannot-have-arrow-having-different-style)

But for the "asynchronous" arrows, I understand that it doesn't make sense...
And on the other hand, is it just a different arrow shape or really an asynchronous typed arrow... _(it's depends of the users...)_

Another pseudo-similar issue will be:
- #1478

Regards,
Th.

**Comment by jimnelson372** [comment]
@The-Lum,

You're right.   It gives the user the choices of arrow types, leaving it to them to decide on the semantics.   For instance, maybe they want to use a double arrowed self-message with a Note to the right to indicate something important is going on in that period of time on the lifeline, rather than meaning it's a two way self message.  Maybe.   And while I would find that confusing, it's up to them.  :)

Jim N.

**Comment by jimnelson372** [comment]
Hello @The-Lum,

I had hoped to get this fix in several weeks ago, but I had to work on other things.    This morning I returned to it and I think it works fine, both in puma and teoz.   Here are the generated diagrams from you script:

Puma:
![testarrow2_001](https://github.com/user-attachments/assets/99555549-dc2b-44af-9bc8-5092eba909c1)

Teoz:
![testarrow2_002](https://github.com/user-attachments/assets/5ace50b0-9096-4eea-8752-38ee8dd39aa7)

I just need to do my final pdiff tests and I'll create the pull request.

Jim N.
