### ISSUE TITLE
not support escape ", suggest using "" mark comments as string

### ISSUE THREAD

**Issue by duguying** [plantuml/plantuml#20]
``` uml
@startuml

[*] --> S0
S0 : 初始状态

S0 --> [*] : EOF

S0 --> S1 : [
S1 --> S0 : ]
S1 : 分组状态

S0 --> S2 : ;#
S2 --> S0 : \\n
S2 : 行注释状态

S0 --> S3 : \\c
S3 --> S4 : =

S5 : 字符串状态
S4 --> S5 : "
S5 --> S4 : "

@enduml
```

the line `S4 --> S5 : "` dose not support escape "(quate mark), I suggest you can change your syntax parser as `S4 --> S5 : "\""`, `S0 --> S1 : "hello, this is a comments string"`

**Comment by dylan-chong** [comment]
@arnaudroques Looks like this issue was forgotten. This looks like a simple thing to fix. Pretty annoying too

**Comment by arnaudroques** [comment]
Yes, this issue has been indeed forgotten. Sorry about that.
About your first post, I'm not sure to understand the issue. Double-quote are working in the following example:
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuOhMYbNGrRLJ23RW2ZPGi59usZ7twVBkvrtRdZKqSe64G98WHLOAhlvkS95WGw10D1UGWcW6ycAvm89FEzgUxsv1Co3O22XZhSm5fE7gOsBokC3YBnRsFDkyucLx5xecOx2gP2uW0ymt0V9jWTAc86lMJd--PjcJ7PkWce2IO3KWEIMG4hWEfPACp68582hFByhEp4jNud98pKi1-Xq0
Note that it is possible that the issue was corrected since August 2016.

About usecase, you can have
```
@startuml
usecase UC1 as "My Usecase with some ()"
@enduml
```
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIejJarEB4vL27KsL4WiLb3ohLG8XGgLPvPaA1JdvwOgQ6WgSJcavgK0DG00

**Comment by dylan-chong** [comment]
Perhaps the quote mark case is a different one.

This example with the brackets will not compile http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuRBoJSpCKt1CoStCir98B8Qmk3H2YrCLIZ9I5H8B2d8oanDBClFpD47I80bDBYuWMQIWQwUWaLzQKfoPaggGL9IOd9rQ0bIGcOSYe0bKxP2QbmAo2m00

**Comment by arnaudroques** [comment]
In that case, you can have:
```
@startuml
:Main Admin: as Admin
(Use the application) as (Use)
usecase use2 as "outside brackets (inside brackets)"

User -> use2
@enduml
```

http://www.plantuml.com/plantuml/uml/LOqn3iCm30DtlKB8L0zPCcOeqWTqx0CKMq259afWoV-Ft4wTIF18S36dwctVO7wIA3xABZeZsS_1xMMC_cQayzmaaykXgUCE4ZJZJD48dNew7CrD2kDQAN_OeoVw5wG18AOLn_jt1GjhYVyB

**Comment by dylan-chong** [comment]
That's an interesting workaround. Any chance you could put some documentation somewhere for that?

Also, I believe this alias situation is where you can't have quote marks

http://www.plantuml.com/plantuml/uml/9Osn3e0W34JtVaN3f8EBeuF13t1qSodIX2O8nkB_2phTvTvBpcgXkpndX6abIRZuKzA4f7-3RbF64XZfkg8SL2Idlk46UdYK3wf6pR6jncM7Ik9nDu5ZpBin05MzSPW_2omdN_zU

**Comment by arnaudroques** [comment]
This is another workaround :-)

```
@startuml
:Main Admin: as Admin
(Use the application) as (Use)
usecase use2 as "bob said <U+0022>hello<U+0022>"

User -> use2
@enduml
```
http://www.plantuml.com/plantuml/uml/DKqx2e0m3DrpYk2aY20THKGFuEW1eWqOgAsOUdzRnUdzUQD6kk9zEEXc4e-JFSHtIFenA1TbZ3iZdQUJZQ84N-Ku1nNSoXkbHaAJtM8DAog9nNwfszQOOMVdmYyAW3Ixi1dU1OpiRVf-0000

I agree that all this should be documented somewhere...

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @duguying, @dylan-chong for the report.
- Thanks PlantUML team for your work.
	
Regards.
