### ISSUE TITLE
Allow plantuml to open/link to other files in the project directory

### ISSUE THREAD

**Issue by johntws** [plantuml/plantuml#2002]
To allow for easier navigation & documentation of plantuml diagrams, is it possible to add a feature that allows plantuml to open other files (or just plantuml) similar to how it works in markdown during preview/render mode?

E.g. in markdown, this will open the `test_file.md` upon clicking the link
```md
[a relative link](path/to/test_file.md)
```

```plantuml
@startuml
Alice->Bob : hello
note left: this is a first note

Bob->Alice : ok

' opens file.puml upon clicking
note right: [[path/to/file.puml link to another puml]]

@enduml
```

**Comment by The-Lum** [comment]
Hello @johntws,

FYI that is already the case:
- Or I misunderstand your question?
- How to use plantuml?
- With a plugin? on a Text Editor?

Because, with other file on a project or with a web URL, plantuml allow this feature, as:
```puml
@startuml
Alice->Bob : hello
note left: this is a first note

Bob->Alice : ok

note right: [[https://github.com/plantuml/plantuml/issues/2002 link to whaterver]]

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/HOqn3eCm34NtIBc3Bq2363CWsciWXa0DiGW9Yarx_IOibVvWsU_v3omkotK4hPw15cpwLvh1WiSGabOn2KB0LIo89uOI1ojb5gWdhRGgVDFVRj7INbUtbMdpHHj7BtAoDMOZyTVyMD9Xpk1YBVqFn7mXcwvjEmWKTv04N-y4ymVpDDMl0yPtGNy0)](https://www.planttext.com/?text=HOqn3eCm34NtIBc3Bq2363CWsciWXa0DiGW9Yarx_IOibVvWsU_v3omkotK4hPw15cpwLvh1WiSGabOn2KB0LIo89uOI1ojb5gWdhRGgVDFVRj7INbUtbMdpHHj7BtAoDMOZyTVyMD9Xpk1YBVqFn7mXcwvjEmWKTv04N-y4ymVpDDMl0yPtGNy0) 

[🔗 link to SVG](https://www.planttext.com/api/plantuml/svg/HOqn3eCm34NtIBc3Bq2363CWsciWXa0DiGW9Yarx_IOibVvWsU_v3omkotK4hPw15cpwLvh1WiSGabOn2KB0LIo89uOI1ojb5gWdhRGgVDFVRj7INbUtbMdpHHj7BtAoDMOZyTVyMD9Xpk1YBVqFn7mXcwvjEmWKTv04N-y4ymVpDDMl0yPtGNy0)


_Perhaps if it is on a render, the issue is more on the plugin and not on the core plantuml project._
Regards,
Th.

**Comment by johntws** [comment]
Hi @The-Lum,

I was able to make it work using the https link, but i'm unable to do so using the file path / name in a project.

I'm not sure if it is a plugin issue, but I tried on both vscode and intellij via the following plugins:
- https://plugins.jetbrains.com/plugin/7017-plantuml-integration
- https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml

**Comment by johntws** [comment]
Hi @The-Lum,

I tried using another plugin and its working as expected.

Thanks for the help.

**Comment by The-Lum** [comment]
Thanks @johntws 

Just for the record:
- What are the plugins?

Regards,
Th.

**Comment by johntws** [comment]
vscode is not working with this plugin https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml. Might also be an issue with vscode itself.

the one that works for me is Intellij + https://plugins.jetbrains.com/plugin/7017-plantuml-integration
