### ISSUE TITLE
Visualize XSDs using PlantUML

### ISSUE THREAD

**Issue by petterreinholdtsen** [plantuml/plantuml#223]
Do you know if there is a way to visualize XML Schemas (aka XSD) with PlantUML?  Is there a script to convert from XSD to the PlantUML notation?

**Comment by ErikAnderson3** [comment]
If nothing exists already, it should be possible to create an XSL transformation to generate PlantUML from an input XSD file.

**Comment by petterreinholdtsen** [comment]
It would be great to have such tool, as I use PlantUML to draw UML diagramsn for the Norwegian archiving standard, https://github.com/arkivverket/noark5-standard, and there is already XSD schemas for all the data structures. :)

**Comment by ErikAnderson3** [comment]
@petterreinholdtsen, jeg kan ikke skrive eller lese Norsk, men jeg kjenne ... a few words, anyway, but if I'm honest, it's from my study of Danish years ago.  :)

More on topic, the "schema" link at the bottom of that page is broken: https://github.com/arkivverket/schema/ just gives a 404.  Digging around, it seems like that should be https://github.com/arkivverket/schemas instead, with an "s" on the end.  I may give a poke, but if I'm honest yet again, my bandwidth is severely limited due to other projects.  That said, I'll chime in if I have anything further to contribute.  Cheers!

**Comment by petterreinholdtsen** [comment]
Thanks for the heads up.  I've fixed the link.

**Comment by aadrian** [comment]
XSD Diagrams would be a cool improvement.

There are already a few libraries that do this, e.g. even Java based: https://github.com/Tblue/xsdvi
so PlantUML would not have to start from scratch.

**Comment by aadrian** [comment]
Another huge advantage of XSD Diagrams would be their use to visualize JSON structures (e.g. using convertors  like https://github.com/ethlo/jsons2xsd )

**Comment by syfds** [comment]
@petterreinholdtsen I'm developing now something similar you describe in your first message: https://github.com/syfds/xsd2plantuml-converter. It's work in progress for now, let me know if you have questions.
