### ISSUE TITLE
Paris Memorial "Easter Eggs"

### ISSUE THREAD

**Issue by mattparkes** [plantuml/plantuml#25]
Whilst a nice thought, the so called 'eggs' module is entirely unnecessary and _extremely unwanted._

Today, any blank/placeholder UML diagrams are instead showing up as the "memorial" for the Paris attacks, as per here: https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/eggs/PSystemMemorial.java

This is very unprofessional.

**Comment by arnaudroques** [comment]
This is supposed to happen only in case of error, and not for any UML diagrams.
Could you give us an example of "blank/placeholder" UML diagrams text, so that we can fix it.
Thanks.

**Comment by freispiel** [comment]
Though I have **zero** tolerance for any kind of violence and appreciate + support the idea of maintaining a memorial of the victims, _this is simply not the place!_

Today this "error message" was showing up on a manager's screen (we are using plantuml as Confluence plugin). Not only did he did not appreciate this, he even informed our security officer about a possible security incident! After all, what does the manager know where the picture is being taken from.
_We might now be forced to ditch plantuml as long as this "feature" still exists!_

Apologies if this is hurting somebody's feelings, but I am fully in agreement with @mattparkes :  "Extremely unwanted" and "very unprofessional" are exactly my thoughts.

_At least make this feature configurable or add a switch ("-noeggs") or whatever._

**Comment by rogeroberg** [comment]
Well we are using the plugin in confluence (The plugin more or less repacks the plantuml library. )
https://marketplace.atlassian.com/plugins/de.griffel.confluence.plugins.plant-uml/overview
, and this "feature" almost breaks the usage now (you see the banner all the time).  
When you add the plantuml container at first you get this picture (since you havn´t started typing the uml, the preview renderer shows the paris text: 
![image](https://cloud.githubusercontent.com/assets/755299/20275418/bd4ce9d6-aa98-11e6-97ac-19bab633aee4.png)

And as soon as you write some error in the uml you get the paris memorial
![image](https://cloud.githubusercontent.com/assets/755299/20275512/1eb8e29c-aa99-11e6-98a1-99a7935e60d4.png)

I really like your plugin and I think it´s a nice thought, but I agree with mattparkes that it´s not proffessional done.

**Comment by mattparkes** [comment]
@arnaudroques, similiar to @rogeroberg, we use PlantUML in Confluence and had the exact same user experience as him.

**Comment by pbennett** [comment]
We even had users  thinking our confluence site had been hacked.  It shows up for blank uml as well.  Just insert the macro and click edit to bring up the dialog.  To say that this behavior is extremely unprofessional is putting it very, very mildly.

**Comment by arnaudroques** [comment]
On second thought:

1) We are going to provide a way to deactivate this feature so that people using the library in official/professional environment won't have those kinds of unwanted behavior. (note that this will remain free)

2) We are going to update our license text ( http://www.plantuml.com/plantuml/png/oybCJirBJWK0 ) to stipulate that in some occasions the library may print some messages or ads and that you can deactivate it.

Since we do not use the Confluence Plugin, we did not realize that the memorial was going to be printed that much (that is while people were typing texts).
This lead us to think about a better integration between PlantUML and Confluence:

3) When an "empty" diagram is displayed, rather than printing an error message (as today). We could print some welcome message (black printed on white background, rather than green on black background). Something like:

```
Welcome to PlantUML

If you use this software, you accept its license (details on http://plantuml.com/license or by typing "license" keyword).

You can start with a simple UML Diagram like:

Bob->Alice: Hello

Or

class String

You will find more information about PlantUML syntax on http://plantuml.com
```
Any suggestion/idea about this welcome text is welcome.

4) About error messages, we realize also that as soon as the user is typing/updating its diagram some error message is printed.
In that case, the current diagram is not shown anymore. So we are thinking about a better way to deal errors.

**Comment by rogeroberg** [comment]
Sounds great @arnaudroques !
We really like the plantuml plugin, and this was almost causing us to have It removed. so if you add the suggested solutions we would be Happy!

Just a clarification, you need to save the page or preview it(in confluence) in order for the plantuml generated image(or error msg) to display.

**Comment by mgriffel** [comment]
@Confluence Users: I just released the plugin version 6.1 that use the older V8036 plantuml library which do not contain the Paris memorial "Easter Eggs". I will update to the latest library version as soon this feature could be deactivated.

**Comment by rogeroberg** [comment]
@mrgriffel I tested the new version and it works great. Thanks for quick support.

**Comment by arnaudroques** [comment]
Finally we've released a new version of the library (V8050) without any date easter eggs, and we won't reintroduce them in the future.

It sounds like the simplest, wisest and best solution.

We also present apologies for people that were hurt : our original intention was not to bother people. We did not envision full impacts of what we were doing.
At least, we have learned something here.

Regards,

**Comment by mgriffel** [comment]
PlantUML Plugin v6.2 for Confluence is now using the latest release of the plantuml library (V8050). Thank you @arnaudroques for the fix!

**Comment by Johnlon** [comment]
Hi is this issue closed now?

**Comment by kevleyski** [comment]
Such a pity, because of _this_ PlantUML is now flagged as malware  and I can't convince people to add it to Confluence now
