### ISSUE TITLE
Need help moving the primary development to GitHub?

### ISSUE THREAD

**Issue by asbjornu** [plantuml/plantuml#32]
As I commented in the [Any plan to move source code to github](http://plantuml.sourceforge.net/qa/?qa=3311/any-plan-to-move-source-code-to-github&show=3332#c3332) thread, I would love to help out with moving the project over from SourceForge to GitHub:

> Is there anything I can do to help moving the active development of PlantUML to GitHub? I'm maintaining and contributing to a number of open source projects there and have been using Git professionally for 5 years, so I would love to contribute and help with the move. Having the source code and development process (issues, discussions, etc.) on SourceForge makes it a lot less visible and harder for people to contribute, I think.

Please let me know if there's anything I can do to assist. I can help out with answering questions, guiding the process to fit Git and GitHub's model, understanding the deal with pull requests, help plan branch strategies, etc. I have great interest in being able to create pull requests myself, so please let me know how I can help

Thanks!

**Comment by trothwell** [comment]
GitHub is great. The migration only has to be done once. And everyone benefits everyday. 😋

**Comment by asbjornu** [comment]
After having discussed this with @arnaudroques, a blocker for moving from SourceForge to GitHub is all the content inside the existing [Q&A Forum](http://forum.plantuml.net/). Without getting this over from SourceForge to GitHub, a move is out of the question as far as I've understood.

So if anyone can help figure out how to convert the Q&A Forum to GitHub issues, that would make the transition much more likely.

**Comment by ScalaWilliam** [comment]
As an aside, I'm working on something-Git that avoids vendor lock-in. Shouldn't have your crucial content locked into proprietary platforms.

**Comment by ScalaWilliam** [comment]
Git has "[notes](http://alblue.bandlem.com/2011/11/git-tip-of-week-git-notes.html)", they are already being used as backend for [git-appraise](https://github.com/google/git-appraise). Would be nice to see people use them fully. So long as our data lives free.. :-)

**Comment by Kernald** [comment]
So... What's the status of this @arnaudroques ? It's been two years since the last update here, and it took me way longer than I would have liked to realise that this repository was basically nothing more than a regular dump of work that's probably done somewhere else (a SVN repository on Sourceforge I assume).

This makes everything harder than it needs to be for:
 - Contributors. The commit history has no valuable information: what "version 1.2019.11" tells you, when you're trying to figure out what's going on in this code base? Even looking at the diff, that's 1000+ lines changed in 63 files (including skins, actual code, Maven coordinates...). The previous commit was twice as big, and the one before that was 6.5k(!) lines.
 - Maintainers. Integrating a PR must be hell, as you need to rebase those patches on your source of trust, which can be vastly different (there was a month and a half between 1.2019.8 and 1.2019.9, during which those 6.5k lines changed without any potential contributor being aware of that).

Also, I don't know what kind of CI you have on the Sourceforge repository, but using PRs on GitHub would have raised the fact that [Travis has been failing for a month](https://travis-ci.org/plantuml/plantuml/builds/575544776). It's now an unreliable signal for any potential contributor.

I get that some parts of the project are historically deeply dependant on Sourceforge. But nothing keeps you from using a single repository for the source itself, and keeping an empty repository on the other platform. Or at least making it clear on GitHub that this is not the main repository.

**Comment by evantill** [comment]
Hi,
We are working hard to make things better.
- We are now using conventional commits to make backlog clearer
- We are automating the release using github workflows and automated changelog is on its way
- We have added github discussions.
- 
Feel free to reopen if needed.
Thank you.
