### ISSUE TITLE
wrong note position

### ISSUE THREAD

**Issue by was4444** [plantuml/plantuml#34]
```
@startuml

B <|-- M
M <|-- D

class B {
  # m_b: int
}
note left of B::m_b
  b
end note

class D {
  # m_d: int
}

note left of D::m_d
  d
end note

B *-- C1
C1 *-- C2

@enduml
```

![err_place](https://cloud.githubusercontent.com/assets/1237906/23244300/eaad1a0e-f949-11e6-967b-41308d9c484e.png)

```
$ plantuml -v
(0.000 - 238 Mo) 232 Mo - PlantUML Version 8056
(0.002 - 238 Mo) 232 Mo - GraphicsEnvironment.isHeadless() false
```

**Comment by arnaudroques** [comment]
Thanks for the report.
Unfortunately, GraphViz sometimes do NOT follow placement directives, and there is not much we can do about this.
Anyway we've just build a new beta that at least draws nicely the note in your example :
https://dl.dropboxusercontent.com/u/13064071/plantuml.jar
The note is still misplaced (right instead of left), but as I said, we have no easy way to fix this.

**Comment by was4444** [comment]
Thanks, @arnaudroques, maybe we can fill a ticket to GraphViz?
