### ISSUE TITLE
No hyperlinks for nested packages in SVG

### ISSUE THREAD

**Issue by mnlipp** [plantuml/plantuml#37]
Since my [comment](http://plantuml.sourceforge.net/qa/?qa=4958/how-to-make-classes-and-packages-clickable-in-html-pages) doesn't seem to have drawn any attention, but mostly because managing issues as comments isn't that good an idea anyway:

Hyperlink generation does not work for nested packages. Here's an example:
```
package org.jgrapes {
    package org.jgrapes.core [[org/jgrapes/core/package-summary.html#package.description]] {
    }

    package org.jgrapes.io {
    }

    package org.jgrapes.http {
    }
}
```

**Comment by arnaudroques** [comment]
Your comment was read: for simplest bug, we prefer to post when the issue is solved and a beta is available. It avoids noise. Of course, it's difficult for people to know if a bug is easy to patch or not. But when it's not, we usually give some answer within few days.

So this should be fixed in last beta https://dl.dropboxusercontent.com/u/13064071/plantuml.jar
Tell us if it's not working for you.
Thanks!

**Comment by mnlipp** [comment]
Version 8059 fixes the issue. Thanks! 

(In case anybody is interested in the sample usage: http://mnlipp.github.io/jgrapes/javadoc/overview-summary.html#jgrapes)
