### ISSUE TITLE
Watchers in Confluence get spammed be each person who views the page

### ISSUE THREAD

**Issue by andreaswalsh100** [plantuml/plantuml#46]
Hi,
A problem we are seeing is that when we have plantuml diagrams on a Confluence page multiple image attachments are generated whenever someone views the page. 
This is resulting in anyone watching the page receiving many notifications that there has been an update, one for each image. 
And this is happening for everyone who views the page. 
The watchers do want to watch the page for edits but don't want to be notified by email 7 times when someone views it. 

Is this a known issue and can it be disabled in some way?

Thanks a lot
Andreas

**Comment by arnaudroques** [comment]
Hi,
Unfortunatly this space is only dedicated to the core PlantUML library or the PlantUML language.
This issue is related to a specific plugin, so you should post your issue on Confluence space
https://marketplace.atlassian.com/plugins/de.griffel.confluence.plugins.plant-uml/server/overview
I'm sure someone there will be able to do something to fix this issue. Sorry about that!

**Comment by andreaswalsh100** [comment]
Thanks. Will try there. 
Regards
Andreas
