### ISSUE TITLE
Regression for default margins

### ISSUE THREAD

**Issue by matthew16550** [plantuml/plantuml#494]
#493 has changed the default margins for Activity & State diagrams:

![comparison](https://user-images.githubusercontent.com/39400458/111743685-2df3c600-88de-11eb-9488-c59cfa0052a9.png)

And #479 for Sequence Diagrams:

![comparison](https://user-images.githubusercontent.com/39400458/111744184-ecafe600-88de-11eb-837c-f9448457d459.png)

All other diagrams seem ok.

**Comment by matthew16550** [comment]
Activity & State is because a call to `SvekResult.calculateDimension()` was [removed](https://github.com/plantuml/plantuml/pull/493/files#diff-fd76c0a39e3296be1b73ef63a8ef560ed40ba359c4d72de1dd77598e7ceb9a5d) from `CucaDiagramFileMakerSvek.createFileInternal()`, I didn't realise it did `moveSvek()`.

```java
public Dimension2D calculateDimension(StringBounder stringBounder) {
	if (minMax == null) {
		minMax = TextBlockUtils.getMinMax(this, stringBounder, false);
		dotStringFactory.moveSvek(6 - minMax.getMinX(), 6 - minMax.getMinY());
	}
	return Dimension2DDouble.delta(minMax.getDimension(), 0, 12);
}
```

Not 100% sure what the `6` and `12` are doing, they are sort of related to the below non-symmetrical defaults in `CucaDiagram` which were [previously](https://github.com/plantuml/plantuml/blob/eea48055d326423a6f29120a3d36fbe0c04216b1/src/net/sourceforge/plantuml/svek/CucaDiagramFileMakerSvek.java#L137) in `CucaDiagramFileMakerSvek.createFileInternal()`.

```java
@Override
public ClockwiseTopRightBottomLeft getDefaultMargins() {
	return ClockwiseTopRightBottomLeft.topRightBottomLeft(0, 5, 5, 0);
}
```

I'm looking into some possible fixes now.

**Comment by arnaudroques** [comment]
> 
> Not 100% sure what the `6` and `12` are doing, they are sort of related to the below non-symmetrical defaults in `CucaDiagram` which were [previously](https://github.com/plantuml/plantuml/blob/eea48055d326423a6f29120a3d36fbe0c04216b1/src/net/sourceforge/plantuml/svek/CucaDiagramFileMakerSvek.java#L137) in `CucaDiagramFileMakerSvek.createFileInternal()`.
> 
> ```java
> @Override
> public ClockwiseTopRightBottomLeft getDefaultMargins() {
> 	return ClockwiseTopRightBottomLeft.topRightBottomLeft(0, 5, 5, 0);
> }
> ```
>

Well I must confess that those  `6` and `12` have been put here just because it was better working this way :-)
Someday, we will remove all those hard-coded values.
This is one reason why I've started the new "style" feature. I wanted all those magic number to be in a [proper config file](https://github.com/plantuml/plantuml/blob/master/skin/plantuml.skin). But this is a long term goal.

> 
> I'm looking into some possible fixes now.
>
Even if you find some _ugly_ solution with your actual refactoring, that's fine.
This will be still better than the actual code.
And we could continue to improve it with another refactoring.

The important point is to reproduce the exact behavior of the actual version.

**Comment by matthew16550** [comment]
I'll go with the simplest for now which is to put the call to `calculateDimension()` back in `createFileInternal()`.

An alternative is tweaking the values in `getDefaultMargins()` which would give us clearer code but `EntityImageDegenerated` sometimes offsets by 7 so it becomes a bit too confusing to try and resolve just now.

The Sequence diagram regression only happens with Puma.   If Teoz is used there is no regression.  This is because before  #479 the default margins were different:
* Puma: `5, 5, 5, 0`
* Teoz: `5, 5, 5, 5`

The default is now controlled by `SequenceDiagram.getDefaultMargins()` which always returns `5, 5, 5, 5`.

Would you like me to change so the earlier different margins are used here?

**Comment by arnaudroques** [comment]
> I'll go with the simplest for now which is to put the call to `calculateDimension()` back in `createFileInternal()`.
> 
> An alternative is tweaking the values in `getDefaultMargins()` which would give us clearer code but `EntityImageDegenerated` sometimes offsets by 7 so it becomes a bit too confusing to try and resolve just now.
> 

Well, I let you choose, but maybe you could go ahead and tweak the values in `getDefaultMargins()` which would clearer code.
`EntityImageDegenerated` is a short-circuit called when there is only one single element (that is "class", "component", "usecase"...) in a diagram. In this degenerate case, there is no need to call `dot` to do some layout because the layout is obvious (since there is a single element).

What I mean is that small changes in rendering with `EntityImageDegenerated` is acceptable since it would only impact tiny diagrams with a single element. So few people will be impacted. And I am quite sure that margins were not perfect anyway nor well managed in that case.

> The Sequence diagram regression only happens with Puma. If Teoz is used there is no regression. This is because before #479 the default margins were different:
> 
> * Puma: `5, 5, 5, 0`
> * Teoz: `5, 5, 5, 5`
> 
> The default is now controlled by `SequenceDiagram.getDefaultMargins()` which always returns `5, 5, 5, 5`.
> 
> Would you like me to change so the earlier different margins are used here?

Yes, please. Because with Puma and Teoz this is a different story : we should really not change the rendering right now.

I don't know if you have seen this, but there is a `modeTeoz()` method in `SequenceDiagram` that you could use to return the appropriate margins.
