### ISSUE TITLE
Java 1.8 source ?

### ISSUE THREAD

**Issue by matthew16550** [plantuml/plantuml#514]
`build.xml` & `pom.xml` put our source level at 1.7 which is more or less at [end-of-life](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) though some enterprise users might still be running it.

I'm writing a few tests that would be much cleaner with 1.8 Lambdas, do we have a plan for when to move to 1.8 ?

**Comment by arnaudroques** [comment]
> `build.xml` & `pom.xml` put our source level at 1.7 which is more or less at [end-of-life](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) though some enterprise users might still be running it.
> 
> I'm writing a few tests that would be much cleaner with 1.8 Lambdas, do we have a plan for when to move to 1.8 ?

Concerning Java version, we try to be **very** conservative. As you may know, some enterprises might still run older versions of Java (although they won't publicly say it :-)  
So we try to support old Java old versions : we think it's important for some of our users. Until recently we were even supporting 1.6 !
Usually, we follow Oracle support roadmap. Since Java 7 extended support runs until July 2022, let's try to wait until July 2022 to fully switch to 1.8

I know this is annoying and we also would love to use new Java features...

However, maybe we can have an intermediate solution : since you are thinking about using Lambda only in tests, do you think it's doable in `pom.xml` to compile main source code in `1.7` and test source code in `1.8` ?

**Comment by matthew16550** [comment]
Yes I've done something similar once before and it seemed to work ok though I was the only person coding there so could never get feed back if it was causing problems for others people.

I'll try in a future PR, it's only a couple of tests so easy to revert if we don't like it.
