### ISSUE TITLE
[discussion] about theme and colors on theme

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#593]
_It is not an issue, but a conversation or discussion about `theme`_

An open question:
_[As you (@bschwarz, @matthew16550) already do PlantUML themes:]_
- Do you know how much color are needed to make a complete theme?

Especially to separate color definition, to theme definition...
In order to be more generic and open theme to other people, just by adding color palette...

_I can analyse all files from [theme directory](https://github.com/plantuml/plantuml/tree/master/themes), but if you have any ideas.._
_The [`plain theme`](https://github.com/plantuml/plantuml/blob/master/themes/puml-theme-plain.puml) is a good starting point... Thanks @matthew16550_

_To open an open discussion..._
Regards.

**Comment by bschwarz** [comment]
There is a [general howto on making your own themes](https://bschwarz.github.io/puml-themes/rolling.html)...at least for the themes I have contributed. All of the color definitions are at the top of the theme files. I did that on purpose so it would be easier to create different themes. I would pick a theme that is the close to what you want, and copy that file. And then change the colors at the top of the file. The [aws-orange theme](https://github.com/plantuml/plantuml/blob/master/themes/puml-theme-aws-orange.puml) is a little more involved because it supports flags that dictate: _dark or light mode_, _background color_, _gradient size_, and _outline flag_. So, if you don't want any of those options, then pick another theme file. Although all of the themes I have done will eventually support those flags as well.

**Comment by matthew16550** [comment]
IIRC all of the themes I made are derived from the `plain` theme.  Generally they use 3 colours - background, foreground and hyperlink.

**Comment by The-Lum** [comment]
Hello @bschwarz, @matthew16550.
Thanks for your answers.
Then, _if have time_, I will plan to create a new similar `~plain theme`, to be more modular with color palettes.

**Comment by The-Lum** [comment]
Issue Review _(with Happy resolution 2023: see [Issue tracking](https://forum.plantuml.net/17257/issue-tracking) [FYI @BenceSzalai])_: 
- This issue can be closed.

_Thanks a lot everybody for your answers._
