### ISSUE TITLE
[Feature request] Refresh on change

### ISSUE THREAD

**Issue by mdziczkowski** [plantuml/plantuml#623]
Please modify the code that it becomes automatically refreshed while editing that the user can see the results without need to press the "Refresh" button every time

**Comment by The-Lum** [comment]
Hello @mdziczkowski,

- Which code do you mean?
- Which PlantUML plugin do you use?

Because:
- For [plantuml/plantuml](https://github.com/plantuml/plantuml)
FYI, with the `plantuml.jar` program there is no `Refresh` button?
_The output is refreshed automatically when we save the input source files._

- For [plantuml/plantuml-server](https://github.com/plantuml/plantuml-server)
If you mean plantuml-server, perhaps ask directly on the [plantuml-server/issues](https://github.com/plantuml/plantuml-server/issues)
See also: plantuml/plantuml-server#44

Regards.

**Comment by mdziczkowski** [comment]
I use the one with is avaliable online on the official server (https://plantuml.com)

**Comment by The-Lum** [comment]
Thanks,

FYI:
- On https://plantuml.com/en/
There is a widget on the bottom, with `AutoRefresh`:
> (You can edit the text if you want, the diagram will be dynamically updated!)

- On http://www.plantuml.com/plantuml/
There is not `Refresh `button, only a `Submit` button.
See the reason here: 
plantuml/plantuml-server#44

If that can help,
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @mdziczkowski for the report.
- Thanks PlantUML team for your work.

Regards.

**Comment by mdziczkowski** [comment]
Thanks 👍
