### ISSUE TITLE
Consuming plantuml to build tools to build something else ...

### ISSUE THREAD

**Issue by rolandtritsch** [plantuml/plantuml#66]
Hi All, 

just noticed that the license on PlantUML is GPL3.

This is no problem as long as you are only using the libs/jar, but becomes a problem, if you want to integrate with it (e.g. building tools, using the API).

I think this will hinder adoption, not foster it.

A lot of companies have policies in place that do not allow to consume copyleft opensource projects.

Would suggest to change the license to something more permissive (BSD, MIT, Apache-2).

Regards ...
    Roland

**Comment by aadrian** [comment]
> just noticed that the license on PlantUML is GPL3.

It's not really GPL, only a small part of it. That's why it's also available as ASL for download:
http://plantuml.com/download#asl

The following proposed refactoring would allow an easy separation of that GPL part (since most users don't need it anyway):
https://github.com/plantuml/plantuml/wiki/Module-Proposal

**Comment by rolandtritsch** [comment]
Aaahhh ... I see/understand. Can you switch the build that is available on the maven repo to the ASL build? And make the GPL build the one to download?

**Comment by arnaudroques** [comment]
We cannot change the build available on maven from GPL to ASL because too many tools are already using it.

However, we could also publish the ASL to maven, but it need some work.
I don't know if we had to publish the ASL sources to SVG/GIT/... Right now ASL sources are only available through a basic download ( http://plantuml.com/download ).

**Comment by rolandtritsch** [comment]
Hi @arnaudroques. Thanks. Yes. I think having an ASL build available on the maven repo would make it easier to adopt plantuml for/in large companies/enterprises. No need to publish the ASL sources on GIT.
