### ISSUE TITLE
plantuml Documentation project

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml#67]
plantuml is an amazing tool and @arnaudroques provides amazing speed of innovation and a great support to developers and requests.

However, plantuml documentation is just sad: extremely outdated and fragmented across several places. I consider myself an advanced user (eg wrote a rdfpuml generator of diagrams from RDF data), and still I'm sadly surprised that I don't know half of its features. Just today I learned of
- Archimate diagrams
- ERD diagrams
- Gantt diagrams
- Tooltips in class diagrams

I mostly use http://plantuml.com/class-diagram, and it doesn't describe all features.
Another complication is that many features are described redundantly, eg Tooltips should be described in one place with a matrix stating where they are supported.

It's obvious to me that plantuml will flourish (people are asking for Venn, MindMaps, etc etc). 
But when something is not documented, it's used by perhaps 1% of the potential users.
Furthermore, plantuml has a peculiar syntax, and if it's not meticulously documented for every feature, people can't use that feature.

So I'm willing to put a lot of time to make proper plantuml documentation, and help @arnaudroques and other contributors keep it up to date.

Sources (ADD MORE if you know others):
- https://github.com/arnaudroques/plantumlguide: latex, 7 years old, quite comprehensive (I can provide a PDF)
- `java -jar plantuml.jar -language`: lists all keywords. 
  Supposed to be completely up to date, but eg PlantUML version 8019 (02 Feb 2015) was missing "skinparam shadowing", "skinparam packageStyle".
- pages at http://plantuml.com (a bit hard to read due to all the ads)
  - Sequence: Basic examples, Declaring participant, Use non-letters in participants, Message to Self, Change arrow style, Change arrow color, Message sequence numbering, Splitting diagrams, Grouping message, Notes on messages, Some other notes, Changing notes shape, Creole and HTML, Divider, Reference, Delay, Space, Lifeline Activation and Destruction, Participant creation, Incoming and outgoing messages, Stereotypes and Spots, Participants encompass, Removing Footer, Skinparam
  - Use Case: Usecases, Actors, Usecases description, Basic example, Extension, Using notes, Stereotypes, Changing arrows direction, Splitting diagrams, Left to right direction, Skinparam, Complete example
  - Class: Relations between classes, Label on relations, Adding methods, Defining visibility, Abstract and Static, Advanced class body, Notes and stereotypes, More on notes, Note on links, Abstract class and interface, Using non-letters, Hide attributes, methods..., Hide classes, Use generics, Specific Spot, Packages, Packages style, Namespaces, Automatic namespace creation, Lollipop interface, Changing arrows direction, Association classes, Skinparam, Skinned Stereotypes, Color gradient, Help on layout, Splitting large files,
  - Activity: Simple Activity, Label on arrows, Changing arrow direction, Branches, More on Branches, Synchronization, Long activity description, Notes, Partition, Skinparam, Octagon, Complete example
  - Activity BETA: Simple Activity, Start/Stop, Conditional, Repeat loop, While loop, Parallel processing, Notes, Colors, Arrows, Grouping, Swimlanes, Detach, SDL, Complete example
    Should be merged to the one above
  - Component: Components, Interfaces, Basic example, Using notes, Grouping Components, Arrows direction, Use UML2 notation, Long description, Individual colors, Sprite in Stereotype, Skinparam
  - State: Simple State, Composite state, Long name, Concurrent state, Arrow direction, Note, More in notes, Skinparam
  - Object: Definition of objects, Relations between objects, Adding fields, Visibility, Defines notes, Use packages, Skin the output, Split the image
  - Deployment: Declaring element, Linking, Packages, Round corner
  - Timing
- extra pages:
  - incubation: mish-mash of new features, should be dispatched to individual pages
  - skinparam: describes params and gives the default values, but is not complete
    A couple years ago there were 342 skinparams. 

I think the best production method is Markdown (though I prefer Org-mode).
@arnaudroques, how do you make the web pages?

**Comment by VladimirAlexiev** [comment]
For better comprehension, I compressed the `skinparam` list in the form of regexps (See below). I use "_" to indicate an empty alternative, and have overgeneralized the regexps a bit in order to keep them simpler.
![image](https://user-images.githubusercontent.com/536250/29868593-2ffb39c4-8d88-11e7-9ab3-c832b4a76333.png)

**Comment by VladimirAlexiev** [comment]
> features are described redundantly

And non-orthogonally. Eg the Class page doesn't say anything about arrow color.
http://plantuml.com/incubation talks of "Change line color in state diagrams". On a hunch, I took the example there and modified it to a [class diagram with arrow colors](http://www.plantuml.com/plantuml/uml/HOx13e8m44Jl-nKalKA2LQy64lw02z1uW7GLazMQietnxwLpyVhUJ6QQJUUewIdK7uhAcQwhwxQzLfUYjq32DtNcooBX0tm4Jczd8llIpzlA7k844H_tLPqFghirYoI6F1CDUU2V7onD88XcCbaQSIAtoYK8w6YfuPVVB_u0) and voila! It works. 

This is a very important feature for me that I completely missed because it's not documented properly.

> webpages a bit hard to read due to all the ads

Another big defect is that there are no anchors.
Eg I can't refer to http://plantuml.com/incubation "Change line color in state diagrams" by a direct URL :-(

**Comment by VladimirAlexiev** [comment]
To be fair, http://plantuml.com/sitemap-language-specification lists Archimate documentation. Because it's not in the top header, it's easy to miss.

**Comment by aadrian** [comment]
@VladimirAlexiev especially sad that ERDs are not documented nor are there any nice examples. 

IMHO it could be the main selling point for PlantUML since most projects with some sort of DB persistence need an ERD to document it.

**Comment by VladimirAlexiev** [comment]
I just found that http://plantuml.com/PlantUML_Language_Reference_Guide.pdf Language Reference Guide is updated to Version 1.2017.15.
So @arnaudroques please accept my apologies for a bit harsh tone above, and an offer for help if you need any with keeping the docs up to date.
Cheers!

**Comment by arnaudroques** [comment]
@VladimirAlexiev No problem! We know that the doc is far from perfect...

**Comment by aadrian** [comment]
@arnaudroques where is the source of the http://plantuml.com/PlantUML_Language_Reference_Guide.pdf so we can contribute to it?

**Comment by arnaudroques** [comment]
@aadrian The situation is complex... There are no raw source for http://plantuml.com/PlantUML_Language_Reference_Guide.pdf 
More precisely, there are a source using an internal custom format that is used to:
* generate the English HTML website
* generate the translation website http://translate.plantuml.com/
* generate the LaTeX English sources of http://plantuml.com/PlantUML_Language_Reference_Guide.pdf 
* generate the translated HTML websites

We thank you for your help proposal.
I think we should rebuild our "custom" format to something more standard (Markdown for example) using https://github.com/vsch/flexmark-java
However, this is a large work, so we probably need contribution here

**Comment by VladimirAlexiev** [comment]
@arnaudroques Single-sourced documentation is the best (esp because you have so many examples, and I am sure you regenerate them automatically). I think we can work with this `flexmark` format. 
Please make a parallel repo `plantuml-doc` and put your doc sources out there, and start accepting contributions.
- I'm sure the ERD users will be glad to document ERD, and the Archimate users to extend that documentation
- I'd like to make some refactorings and elaboration on particular issues.

For example, today I'll spend an hour figuring out how to check the puml and dot versions of a newly installed server.
- found `testdot` but that gives only dot version
- this command is not listed in `java -jar plantuml,.jar -language`
- still looking how to get the image with puml version info. Aha, on a hunch it's the `about` command.

**Comment by weedySeaDragon** [comment]
If I possibly can, I would be happy to help with the documentation.  I totally agree with @VladimirAlexiev -- PlantUML is powerful, but the doc has not kept up.  

Would be great to generate the documentation based on the codebase.  This will assume that the appropriate info and some markup is in the code, but more than pays off with the all of the advantages and labor saved with having a single source.

**Comment by weedySeaDragon** [comment]
Yet another thought:  [Sphinx](http://www.sphinx-doc.org/en/stable/index.html)  is used to generate documentation and websites.  It's easy to put it into a `maven` or `ant` workflow.  
At it's simplest, it takes markup files and generates output (HTML, text, and PDF via LaTeX). It supports internationalization (translations).   

There are lots and lots of plugins that can do things like _process source code as part of the input to the documentation._  That means that **the source code can be the single source of information for the documentation content.**  (Of course you also provide things like HTML templates so that you can generate your website as you want it, etc.)

There's even a plug-in that can read PlantUML files and insert the diagrams.

I've forked this repo and am playing with it on my local machine.

**Comment by VladimirAlexiev** [comment]
As @arnaudroques wrote above, he's using an internal custom format and plans to perhaps convert it to Markdown using a Java implementation.
Sphinx uses Restructured Text and is implemented in Python, so it may or may not be useful. Its particular strength is in defining a document tree/TOC and hyperlinks between doc modules.

**Comment by weedySeaDragon** [comment]
Sphinx _can_ use markdown as input.  And there's a maven plugin so that you can run Sphinx as part of the workflow: https://trustin.github.io/sphinx-maven-plugin/index.html
That plugin also gives you the ability to incorporate plantuml right into the documentation (using rST).

Right now on my local machine, the maven task `site` runs Sphinx to generate some simple site pages.

So it might be possible to get the output of `java -jar plantuml.jar -pattern` and turn that into rST (doing some basic substitutions on the regexp patterns to turn it into something 'end-user readable').  Or take the output of `java -jar plantuml.jar -help` for a page on all of the command-line stuff.

But -- I'm just suggesting Sphinx as a possibility.  It may not be the right tool for the job.

(IMHO, Sphinx has many more strengths than just a document tree. YMMV)

**Comment by albfan** [comment]
@arnaudroques http://translate.plantuml.com/ looks a lot like sphinx-intl 

https://pypi.python.org/pypi/sphinx-intl

See https://bugzilla.gnome.org/show_bug.cgi?id=789008

for an example usage. I guess generated po files can be reworked for that frontend

For sphinx and plantuml integration see readthedocs

http://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/UsingGraphicsAndDiagramsInSphinx.html#using-plantuml

It is just add 

    extensions = ['sphinxcontrib.plantuml']

to conf.py

Then you can have a great documentation on a responsive website and pdf or other formats if you like too

Let me know if you want to migrate, I would love to help out

**Comment by arnaudroques** [comment]
To help us to improve the documentation, we have just put in place a Wiki here: http://wiki.plantuml.net
This is really a try and we expect this wiki to be the single source of documentation in some future.

**Comment by Potherca** [comment]
I know this might not be a popular opinion but I would _strongly_ advise against (ab)using a wiki for documentation.

The major drawback are:

- Yet another platform is added (next to a website, a separate PDF, a forum and a repo).
- Yet another complex syntax is added. [Wiki markup](https://en.wikipedia.org/wiki/Help:Wikitext) is a complex and very broad language. Because it is available people _will_ start using the more advanced features, making it ever harder to transpile into other formats.
- Wiki-as-docs is a extremely rare occurrence, especially for something that is (by and large) a technical product. 
- The wiki can not (easily) be used locally. (Either to read or to edit).
- One can not easily `grep`, `ack` or otherwise mechanically search or scan a wiki.
- It is a lot harder to get an overview of who has edited what (and when (and why (etc.))).
- It is impossible to reference or make a connection between certain issues in this repo and changes in the docs, other than manually.
- A wiki is basically just pages that live in a root space with links between them. There is no structure.

I would very strongly advise to use a more common solution instead, like a separate repo, the Github Wiki, [readthedocs](https://readthedocs.org) or any other simple-markup oriented solution.

Consider: the documentation for an open-source project the scale of PlantUML is a project in its own right.  It is a lot easier for contributors to make additions and changes through the Github platform than in a wiki. It is also a lot easier from a maintainers perspective to keep track, delegate tasks and orchestrate contributions here.

I know this is not my place to make demands but I would _really_ _**really**_ strenuously ask you to reconsider using a wiki.

**Comment by VladimirAlexiev** [comment]
- Another problem with the wiki is that there's no global index/TOC.
  Then again, the website has a similar problem, eg http://plantuml.com/pte has breadcrumb "PlantUML> News and information> PlantUML Text Encoding" but this should be somewhere under Server, not under News
- @arnaudroques what is your plan to merge wiki contributions to the website & documentation? Eg 
http://wiki.plantuml.net/site/plantuml-text-encoding is now richer than http://plantuml.com/pte, but is there some sort of relation between the two URLs?
- How can one discover related material and make links? Eg I remember that puml stores the text-encoding inside the png and there's a way to ask the server to extract it and show the diagram source. But I don't know how to find this feature nor how to link it to the "PlantUML Text Encoding" page

**Comment by arnaudroques** [comment]
@VladimirAlexiev Yes http://wiki.plantuml.net/site/plantuml-text-encoding is supposed to be the source of http://plantuml.com/pte so there is an issue here. I'll investigate about this.

**Comment by VladimirAlexiev** [comment]
Aha! And I added a link from http://wiki.plantuml.net/site/plantuml-text-encoding to http://wiki.plantuml.net/site/server#metadata:

"The encoded metadata is stored in the generated PNG, so the diagram source can be extracted from the diagram itself!! (see metadata)."

**Comment by arnaudroques** [comment]
@Potherca Ok I agree with you on this:

> Consider: the documentation for an open-source project the scale of PlantUML is a project in its own right. It is a lot easier for contributors to make additions and changes through the Github platform than in a wiki

I really like to set PlantUML documentation as a project on its own.
My biggest concern is that today the documentation (although incomplete) is partially translated in French/Spanish/German/Japanese/Chinese/Korean/Russian so this something I would like to keep. And I did not find any tool that would allow collaboration and **easy** translation. That's why I've tried DokuWiki : its translation plugin looks fine.

But if someone find some better way to manage those translations using GitHub, that would be something I could put in place.

**Comment by arnaudroques** [comment]
@VladimirAlexiev and you can use -encodeurl or -decodeurl in the command line flags to encode or decode the text.

**Comment by VladimirAlexiev** [comment]
Made some edits, the wiki isn't that bad at all! It is very accessible even to non-tech users. The main shortcoming is that there's no TOC/tree, but we can make one!

I think that improving the master documentation (English) and translating it are two separate tasks, and they shouldn't be intermixed. I.e. we should run a half-year English doc improvement effort, after which organize translation efforts.
- Of course, the current translations must be preserved at all cost.
- I've never used it, but many projects use Transifex for translation...

**Comment by arnaudroques** [comment]
@VladimirAlexiev pte is now on http://plantuml.com/text-encoding

So I've create a test project https://github.com/plantuml/wiki1 with current wiki sources. So maybe it will give some ideas to someone on how **easily** manage translations, which is my first concern.

**Comment by aadrian** [comment]
@arnaudroques very good step. What wiki syntax is using however?

**Comment by arnaudroques** [comment]
@aadrian It's DokuWiki syntax (see http://wiki.plantuml.net/wiki/syntax )
Note that I'm testing DokuWiki now because its translation feature seems to be the most adapted to PlantUML needs, even if it's far from perfect.

**Comment by mlopezgva** [comment]
If it is going to remain in its own server (it is only fair...), I suggest the creation of a documentation site using _bootmark_, _strapdown_ or anything with similar functionality (to mix many sources into one big page with side index and anchors everywhere).

It would be easy to maintain and to update, and adding section auto-numbering, etc.

AsciiDoc is more powerful than markdown and also allows having a TOC an other niceties.

Ads can be added, too, because these libraries act upon a single HTML element, and anything else is only altered by the CSS (bootstrap in both cases).

There must be a TODO control list for all the things that needed to be documented.

**Comment by weedySeaDragon** [comment]
@mlopezgva - Sphinx does all of that.  It produces a TOC and an _index_ (which I think is critical).  You can create different formats (html, pdf, etc) as needed.  And it's been in use for years and has a very large user base.
https://read-the-docs.readthedocs.io/en/latest/  works with sphinx: you can use it to generate a website based on source in a github repo (via a webhook)
 

I've started some documentation with it:  https://plantuml-documentation.readthedocs.io/en/latest/

**Comment by mlopezgva** [comment]
The main difference, as see it, is that with Sphinx the site must be generated each time there is a change in a source file, while using some of the others (asciidoc or markdown, or even rst if I'm not mistaken), the site is generated on-the-fly, there's no pre-processing, compiling etc. OK, it is only necessary when the documentation source changes, not every time a page is presented (if I got it right). And, of course, it is perfectly feasible to automate it.

From my point of view, having "only" the `[page_name].{md,rst,adoc}` files categorized by the directory structure as source of the project is as easy as it can be, and a simple front-end to parse them client-side makes it even lighter to the server. also, making changes means having to change exactly the file which needs to be changed, no more; no compiling, no extra processing at all, just a git push to the server from the repository.

I could even argue no java or java-only-web-server is needed, but since plantuml is already a web java server, that's no point in favor here.

Creating a PDF, man pages etc. could be done using pandoc or asciidoc[tor]. Here there is really a need to run the compiler on each commit to keep the links synced, just like with Sphinx... But only for those formats, not for the web.

---

But, it is just my opinion. More people have more experience with these and many other tools. I just like to keep far away from java. :-)  (our local plantuml server runs with Apache server and 50 lines of script code, no Tomcat or Jetty there...).

**Comment by weedySeaDragon** [comment]
2 separate issues:

1. Sphinx does _not_ need to run every time a page is presented.  It simply generates the output, be it html or pdf or whatever.  If it's html, then just like any other site, it's up to the webserver to present it.

2.  Which tools to use (sphinx or whatever):  I think first an agreement as to what the _requirements_  and _constraints_ are is needed.  Then the appropriate tool can be chosen. 

For complete user documentation, an index is necessary.  One critical function that an index provides that is often overlooked  is that it provides _a list of what is possible and available_.  (A table of contents provides a very small version of this.)  This is a critical and substantial portion of information that has been missing from PlantUML.

_I'm unfortunately short on time ATM. We need to agree first on the requirements and constraints.  Here's a short list just as a start:_

### Requirements
- TOC
- index
- TODO list
- i18n
- automatic generation
   - github webhook support (e.g. to kick off automatic generation)

### Constraints
- are there platforms that this _must_ run on? (e.g. what those that will support this are familiar with)
- programming language constraints?  (e.g. what those that will support this are familiar with)
- cost 
   - must be free?

**Comment by mlopezgva** [comment]
Hi!

OK, so Sphinx is like Asciidoc, translates RST files into HTML, is not a "live" presenter. I thought it was. Sorry.

Indexing is also possible in asciidoc, but, if rst is preferred, then so be it. I think github also accepts RestructuredText

**Comment by VladimirAlexiev** [comment]
I've been contributing documentation to the doc wiki http://wiki.plantuml.net/site/index: it works very well! Now most website pages have a link "You can contribute on this page by clicking here".

So let's close the discussion about other documentation toolkits and workflows, be thankful to @arnaudroques and get to work!

@aadrian @albert-github @weedySeaDragon @albfan @Potherca @mlopezgva @mhaaz: plantuml has a bunch of undocumented features listed at https://forum.plantuml.net/7095, https://forum.plantuml.net/7140 thanks to @Anthony-Gaudino. I think the first urgent task is document all these. All of them have a working diagram towards the end, so it's a "simple" matter of:
- understanding what the feature is
- finding a spot for it (we could lump it all to a new page "Undocumented features" but that's not optimal)
- figuring out what other features to group with
- describing it
- including the working diagram (there are many examples how to do it, with source on the left and diagram on the right)
- optionally, improving the diagram for maximum pedagogical effect

Any volunteer to organize the work?
- I think we want a separate project on github so as not to pollute this one with issues
- someone to transcribe the two "undocumented" lists as github issues?
- some planning page to coordinate the work
- any volunteer to coordinate?

@arnaudroques you could help us by:
- creating this separate project and adding a few people as contributors, so we can handle issues
- adding some macro to the wiki so we don't have to copy every diagram twice: instead of this

```
<columns 100% 50% ->
<code>
@startuml
...
@enduml
</code>
<newcolumn>
<uml title="foo">
...
</uml>
</columns>
```

I want to write just that:
```
<puml>
...
</puml>
```

- improving synchronization. Eg http://wiki.plantuml.net/site/sequence-diagram is definitely not the same as http://plantuml.com/sequence-diagram
- improving the TOC on both website and wiki, eg see https://forum.plantuml.net/10159/doc-more-complete-sitemap
- last but not least, how can you help you to streamline the approval process from wiki to website, to lessen your workload

**Comment by VladimirAlexiev** [comment]
> I compressed the skinparam list in the form of regexps

Now updated at https://github.com/VladimirAlexiev/plantuml-skinparam

**Comment by VladimirAlexiev** [comment]
Set up a channel at https://app.slack.com/client/TL8BFRV6G/CNN19STHC/thread/CKY153BDY-1563199828.000900

**Comment by VladimirAlexiev** [comment]
Posted detailed task list https://github.com/plantuml/plantuml/issues/261

**Comment by VladimirAlexiev** [comment]
Thanks to Arnaud, it's now really easy for people to contribute doc additions and fixes using their favorite syntax. Most of the important [Wanted Features](http://alphadoc.plantuml.com/doc/markdown/en/start#txoy6i3x04itk2mb5w8i) are now implemented, and Arnaud will be adding more. 
I'll close this issue because I think most features discussed above are summarized well by Arnaud in this link. If I missed something, please add it to that link, pointing back to the more detailed discussion here.

Now it's time for the community to step up and help Arnaud document this wonderful program better! Eg help by working on the 100-200 categorized tasks in #261
