### ISSUE TITLE
teoz: activation breaks parallell lines

### ISSUE THREAD

**Issue by chipbite** [plantuml/plantuml#739]
Hello!

Strangely, when using activation, it interferes with teoz rendering, so that messages using &, despite that do not render on same row.
**Example:**

```plantuml
@startuml
!pragma teoz true
autonumber 
AAA -> BBB++: Message 0
BBB -[#22A722]> DDD: Message 1
deactivate BBB
activate DDD
& DDD -> EEE: Message 2
note right #red: <-- Expect 1 & 2 to be same row
DDD -[#22A722]> FFF++--: Msg 3
& FFF -> GGG--: Msg 4
note right #red: <-- Expect 3 & 4 to be same row
@enduml
```

![image](https://user-images.githubusercontent.com/559199/139748281-5b6f21b5-e0b9-4c33-9996-e5e4984420ff.png)

Here is rendering:
![image](http://www.plantuml.com/plantuml/png/VP1FIyD04CNlyocU57e92tPR48gK9kJFoKyW7gRD40icMtOdAdvwPmyQzD3Bmhvvx_s6EIRbgFFuHdVNoCF8K0bVq3WByQnXciUJH51Pbd07L5LL57iyIKey2Ex91BZdbVVbW_Sl1zHrlOmtr0kVzVBEAZbAln-pqJg_kRHfcYNZQGfcY9VXLR6Aqk_nw1oQpwkS5HkiuQ419q7YqNpXWwpcpmvjsnQ5SzQP1coDOqBcT5tte-vkKhP6sVsd76NgxKxV)

[Link to this example on plantuml server](http://www.plantuml.com/plantuml/uml/VP1FIyD04CNlyocU57e92tPR48gK9kJFoKyW7gRD40icMtOdAdvwPmyQzD3Bmhvvx_s6EIRbgFFuHdVNoCF8K0bVq3WByQnXciUJH51Pbd07L5LL57iyIKey2Ex91BZdbVVbW_Sl1zHrlOmtr0kVzVBEAZbAln-pqJg_kRHfcYNZQGfcY9VXLR6Aqk_nw1oQpwkS5HkiuQ419q7YqNpXWwpcpmvjsnQ5SzQP1coDOqBcT5tte-vkKhP6sVsd76NgxKxV).

If you comment out activation, (lines 8 & 9 and ++-- on line 12) it is rendered as expected.

Thanks for a great tool!

BR! /mawi

PS 
This is same as https://forum.plantuml.net/14873/teoz-activation-breaks-parallell-lines

**Comment by jhoehle** [comment]
Coming to think about the last part:
```
DDD -[#22A722]> FFF++--: Msg 3
& FFF -> GGG--: Msg 4
```
This ought to signal the error "Activation/Deactivation already done on FFF".

**Comment by jimnelson372** [comment]
I've been looking into the issues related to the active timelines drawing in the wrong place when --++ is used and in some cases involving parallel messages (see #1494).   While examining parts of the parallel message implementation, I found the cause of this one. 

I have a fix that I am preparing to include with several other related fixes.   I wanted to share what the script in this issue now generates when this issue is fixed.  Using the exact script, no changes at all:

![testteoz](https://github.com/plantuml/plantuml/assets/66284321/bbdf6898-5141-462e-99c0-16353b77bb54)

The start and end of the active level for D is now much cleaner.

And it now also works using ++-- on line 5, instead of the two activate instructions one lines 6 & 7.

One issue I'm still tracking down, though, is what happens if line feeds are used in the message text shown in issue #656.  

Regards,
Jim Nelson

P.S. I haven't yet looked at whether there should be an error reported, as mentioned in the comment by @jhoehle above.

**Comment by chipbite** [comment]
1. Thanks for the update and work on this set of issues @jimnelson372!  That sounds truly **awesome**! 💪 ❤️ 👍 

These bugs have been around for rather long, and I suspect they might actually hurt adoption of lifelines activation usage. The shorthand (`++`/`--`)  is the way to go, IMO: The explicit `activate`/`deactivate` declarations are IMHO far too cumbersome and inflate the diagram source size making it harder to overview, read and follow.

2. Thanks also to you @jhoehle, for this comment:
> Coming to think about the last part:
> 
> ```
> DDD -[#22A722]> FFF++--: Msg 3
> & FFF -> GGG--: Msg 4
> ```
> This ought to signal the error "Activation/Deactivation already done on FFF".

Agreed, yet - somehow - this feels not so clear cut to me. This could work, definitely. Maybe it is the best. 

_My thoughts:_ On the one hand, I think errors should be reserved for when the illustration cannot be rendered. It feels like to a large extent, this is how plantuml handles things, but I am not sure - just a gut feeling. The image gets rendered as best it can, warts and all. Not sure if that is right?
OTOH, therein lies the problem, ofc: For most users, there is no other channel to use for plantuml to signal to the user that there is an issue. 
So, failfast or act graciously/defensively producing a result based on what is there?

Not sure if there is a principle that the project has defined for cases such as this, I suspect there might be. I would be interested in learning about it, if so.
