### ISSUE TITLE
from command line: NPE on Unix

### ISSUE THREAD

**Issue by patrickp-at-work** [plantuml/plantuml#857]
I've mavenized my plantuml generation (i.e. invoke `plantuml.jar` from my `pm.xml` through the `exec-maven-plugin` plugin). On my local Win 10, it works fine. On the CI machine (running some Unix), it throws the following NPE.
```
Exception in thread "main" java.lang.NullPointerException
	at net.sourceforge.plantuml.FileGroup.initWithDoubleStar(FileGroup.java:149)
	at net.sourceforge.plantuml.FileGroup.recurse(FileGroup.java:83)
	at net.sourceforge.plantuml.FileGroup.<init>(FileGroup.java:63)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:394)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:369)
	at net.sourceforge.plantuml.Run.main(Run.java:204)
[main] ERROR org.codehaus.mojo.exec.ExecMojo - Command execution failed.
```

Supplied argument for inputs is `"${project.basedir}/some-folder/another-folder/*/*.puml"`. As instructed by [the manual](https://plantuml.com/en/command-line).
For outputs, I use `-o ${project.build.directory}/plantuml`

The double star syntax yielded the same NPE with a different stack trace.

Tested with versions 1.2022.0 and 1.2021.13

I guess I am missing something?

**Comment by arnaudroques** [comment]
> I guess I am missing something?

Well, so are we :-)

How can we have a NullPointerException in [L149](https://github.com/plantuml/plantuml/blob/f83a207360011e575046becb056f5f84104656b2/src/net/sourceforge/plantuml/FileGroup.java#L149) ?

The only call is done in [L83](https://github.com/plantuml/plantuml/blob/f83a207360011e575046becb056f5f84104656b2/src/net/sourceforge/plantuml/FileGroup.java#L83) and `parent` could not be `null` since it's initialized in [L79](https://github.com/plantuml/plantuml/blob/f83a207360011e575046becb056f5f84104656b2/src/net/sourceforge/plantuml/FileGroup.java#L79) or [L81](https://github.com/plantuml/plantuml/blob/f83a207360011e575046becb056f5f84104656b2/src/net/sourceforge/plantuml/FileGroup.java#L81).

We might add a protection again NPE, but we are definitively missing something here.

**Comment by arnaudroques** [comment]
> How can we have a NullPointerException in [L149](https://github.com/plantuml/plantuml/blob/f83a207360011e575046becb056f5f84104656b2/src/net/sourceforge/plantuml/FileGroup.java#L149) ?
> 
> The only call is done in [L83](https://github.com/plantuml/plantuml/blob/f83a207360011e575046becb056f5f84104656b2/src/net/sourceforge/plantuml/FileGroup.java#L83) and `parent` could not be `null` since it's initialized in [L79](https://github.com/plantuml/plantuml/blob/f83a207360011e575046becb056f5f84104656b2/src/net/sourceforge/plantuml/FileGroup.java#L79) or [L81](https://github.com/plantuml/plantuml/blob/f83a207360011e575046becb056f5f84104656b2/src/net/sourceforge/plantuml/FileGroup.java#L81).

... except if `currentDir.listFiles()` itself is null

"When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth."

We're going to fix it :-)

**Comment by patrickp-at-work** [comment]
I have removed all the stars from the input, now it works flawlessly both locally and on the CI node.
So it must be related to the star syntax that I have used.
About the (recursive) invocation of the method, I'm not sure.

**Comment by arnaudroques** [comment]
It would be nice if you could [test last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) and tell us if it's working now.
Thanks!

**Comment by patrickp-at-work** [comment]
Using the -SNAPSHOT release, the NPE is not reproducible for me. The invocation on my local is unchanged. On the CI node, it outputs
```
No diagram found
```
I assume for now that this is a truthy statement, possibly indicating that there is something wrong with my maven / CI setup which prevents plantuml.jar from finding the puml files.
