### ISSUE TITLE
Dot not found even when in the PATH

### ISSUE THREAD

**Issue by dawagner** [plantuml/plantuml#9]
From what I can read in the documentation and the code, `dot` is only searched in a few hardcoded places and in the `GRAPHVIZ_DOT` variable. IMHO, it should be searched in that order:
- `GRAPHVIZ_DOT`
- let the system find it (just run `dot`)
- search for it in select places (actually, I don't think it makes sense to do that on Linux)

I'm running into this issue on Windows in the following use-case:
- I have dot in the `PATH` (but not in c:/program files)
- I'm using plantuml through doxygen
- In my build script, I don't want to hardcode the path to `dot`

**Comment by ShoggothPete** [comment]
Another example of 'Dot executable: C:\ProgramFiles\Graphviz2.38\bin\dot  File does not exist Cannot find Graphviz. ' is reported for windows state diagrams via doxygen at http://forum.plantuml.net/7188/issue-in-generating-state-diagrams-with-doxygen .

**Comment by joaoe** [comment]
I just hit this problem. I spet hours debugging why plantuml was not picking up my locally installed dot.exe. 

The issue
https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/cucadiagram/dot/GraphvizWindows.java#L50
https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/cucadiagram/dot/GraphvizLinux.java#L49

I'l suggest this: this is how you search for exectuables
https://stackoverflow.com/a/32827512

**Comment by joaoe** [comment]
Btw, for those looking for a workaround, set the GRAPHVIZ_DOT environment variable or the java property with the same name like
```
System.setProperty("GRAPHVIZ_DOT", "/home/<user>/projects/graphviz/build/bin/dot");
```

**Comment by arnaudroques** [comment]
@joaoe  Sorry about hours spent in debugging :-(
We are now using https://stackoverflow.com/a/32827512
So in last beta http://beta.plantuml.net/plantuml.jar

Exe is searched:
  - First using GRAPHVIZ_DOT variable
  - Then in the PATH
  - Then using hardcoded value /usr/local/bin/dot  /usr/bin/dot /opt/local/bin/dot c:/program files and c:/program files (x86)  

We are still testing this because it may impact some users. It is however more logical to find in the PATH *before* using hardcoded value.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered and fixed.
- Thanks @dawagner for the report.
- Thanks @joaoe for your answer.
- Thanks PlantUML team for your work.

Regards.
