### ISSUE TITLE
Support Allman brace style

### ISSUE THREAD

**Issue by evandrocoan** [plantuml/plantuml#99]
If I use `Allman` brace style: https://en.wikipedia.org/wiki/Indentation_style
```java
@startuml
scale 750 width

package foo1 <<Node>>
{
    class Class1
}
@enduml
```

I got error when building:
```
Rendering [(<PlantUmlDiagrams.diagram.plantuml.PlantUMLProcessor object at 0x05F347D0>, ['@startuml\nscale 750 width\n\npackage foo1 <<Node>>\n{\n    class Class1\n}\n@enduml\n'])]
Rendering diagram for block: '@startuml\nscale 750 width\n\npackage foo1 <<Node>>\n{\n    class Class1\n}\n@enduml\n'
chdir to: F:\SublimeText\Data\Packages\PlantUmlDiagrams\samples
Error Processing Diagram:
@startuml
scale 750 width

package foo1 <<Node>>
{
    class Class1
}
@enduml
```

Only K&R works:
```java
@startuml
scale 750 width

package foo1 <<Node>> {
    class Class1
}
@enduml
```

![image](https://user-images.githubusercontent.com/5332158/36082310-7b1ebc8a-0f8f-11e8-9202-e44ffdf7c0e4.png)

**Comment by marius63** [comment]
This issue should be top priority RIGHT NOW.
Unless this is solved there's no way PlantUML can be considered "serious."
It's a pity because there is so much potential and traction.
If someone would point me to the syntactical component or class I'll have a try. (The source code directory names are cryptical, and there's no architecture, and it is not clear if the "master" is sourceforge or github, and all these are important issues on their own, but of secundary importance relative to this.)

**Comment by arnaudroques** [comment]
Ok, since this seems important for many people, we have started to implement this.
Due to internal way of parsing texts in PlantUML (massive use of regex), it's not that easy to do.
However, we have find a way that needs some delicate refactoring.
So with last beta http://beta.plantuml.net/plantuml.jar the first example is now working:

```
@startuml
scale 750 width

package foo1 <<Node>>
{
    class Class1
}
@enduml
```
We are going to extend this, but we need to do our refactoring first.
Please be patient, we'll post a message here (in a couple of week) when this will be ready.

**Comment by marius63** [comment]
Outstanding!
This single change allows us to continue to use plantUML.
/* Word of advice: regex sucks at "massive use" and language parsing. Consider replacing it with a dedicated hand made state machine, like compilers do. Since you are refactoring... But first setup a test set if you have not already done so. */

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @evandrocoan, @marius63 for the report.
- Thanks PlantUML team for your work.

Regards.
